//! C code generation backend for AOT compilation.
//!
//! Translates MIR (SSA-form IR) into C99 source code that can be compiled
//! with gcc/g++ -O2 for native performance. This bypasses the LLVM dependency
//! and gives access to g++'s optimizer, which outperforms LLVM on x86_64
//! for certain patterns (recursive inlining, x86-specific codegen).
//!
//! Pipeline: MIR → C source → gcc -O2 → native binary (linked with librayzor_runtime.a)

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::fmt::Write;

use crate::ir::blocks::{IrBlockId, IrPhiNode, IrTerminator};
use crate::ir::instructions::{BinaryOp, CompareOp, IrInstruction, UnaryOp};
use crate::ir::modules::IrModule;
use crate::ir::{IrFunctionId, IrGlobalId, IrId, IrType, IrValue};

/// C code generation backend.
pub struct CBackend {
    /// Accumulated C source output.
    output: String,
    /// Current indentation level.
    indent: usize,
    /// MIR function ID → C function name.
    function_names: BTreeMap<IrFunctionId, String>,
    /// Extern functions already declared (by name).
    declared_externs: HashSet<String>,
    /// Functions whose bodies have been emitted.
    emitted_functions: HashSet<IrFunctionId>,
    /// Global variable declarations needed.
    used_globals: BTreeSet<IrGlobalId>,
}

impl CBackend {
    fn new() -> Self {
        Self {
            output: String::with_capacity(64 * 1024),
            indent: 0,
            function_names: BTreeMap::new(),
            declared_externs: HashSet::new(),
            emitted_functions: HashSet::new(),
            used_globals: BTreeSet::new(),
        }
    }

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    /// Generate a complete C source file from MIR modules.
    pub fn emit_modules(
        modules: &[IrModule],
        entry_func: &str,
        startup_funcs: &[String],
    ) -> Result<String, String> {
        let mut backend = Self::new();

        // Phase 1: Assign C names to all functions
        backend.assign_function_names(modules);

        // Phase 2: Emit preamble
        backend.emit_preamble();

        // Phase 3: Emit extern declarations for runtime functions
        backend.emit_extern_declarations(modules);

        // Phase 4: Emit forward declarations for all internal functions
        backend.emit_forward_declarations(modules);

        // Phase 5: Emit function bodies
        for module in modules {
            for (func_id, function) in &module.functions {
                if function.cfg.blocks.is_empty() {
                    continue; // extern/declaration only
                }
                if backend.emitted_functions.contains(func_id) {
                    continue;
                }
                backend.emit_function(*func_id, function)?;
                backend.emitted_functions.insert(*func_id);
            }
        }

        // Phase 6: Emit main() wrapper
        backend.emit_main_wrapper(entry_func, startup_funcs);

        Ok(backend.output)
    }

    // -----------------------------------------------------------------------
    // Phase 1: Name assignment
    // -----------------------------------------------------------------------

    fn assign_function_names(&mut self, modules: &[IrModule]) {
        let mut name_counts: HashMap<String, usize> = HashMap::new();

        for module in modules {
            for (func_id, function) in &module.functions {
                let mut base_name = Self::sanitize_name(&function.name);
                // Rename "main" to "_haxe_main" to avoid conflict with C main()
                if base_name == "main" {
                    base_name = "_haxe_main".to_string();
                }
                let count = name_counts.entry(base_name.clone()).or_insert(0);
                let c_name = if *count == 0 {
                    base_name.clone()
                } else {
                    format!("{}_{}", base_name, func_id.0)
                };
                *count += 1;
                self.function_names.insert(*func_id, c_name);
            }
        }
    }

    fn sanitize_name(name: &str) -> String {
        name.replace("::", "_")
            .replace('<', "_L_")
            .replace('>', "_R_")
            .replace(',', "_C_")
            .replace(' ', "_S_")
            .replace('.', "_")
            .replace('-', "_")
    }

    // -----------------------------------------------------------------------
    // Phase 2: Preamble
    // -----------------------------------------------------------------------

    fn emit_preamble(&mut self) {
        self.emit_line("/* Generated by Rayzor C backend — do not edit */");
        self.emit_line("#include <stdint.h>");
        self.emit_line("#include <stddef.h>");
        self.emit_line("#include <string.h>");
        self.emit_line("#include <stdlib.h>");
        self.emit_line("#include <math.h>");
        self.emit_line("");
        // Type aliases
        self.emit_line("typedef int8_t i8;");
        self.emit_line("typedef int16_t i16;");
        self.emit_line("typedef int32_t i32;");
        self.emit_line("typedef int64_t i64;");
        self.emit_line("typedef uint8_t u8;");
        self.emit_line("typedef uint16_t u16;");
        self.emit_line("typedef uint32_t u32;");
        self.emit_line("typedef uint64_t u64;");
        self.emit_line("");
        // Bitcast helper
        self.emit_line("static inline double _bitcast_i64_to_f64(i64 v) { union { i64 i; double f; } u; u.i = v; return u.f; }");
        self.emit_line("static inline i64 _bitcast_f64_to_i64(double v) { union { i64 i; double f; } u; u.f = v; return u.i; }");
        self.emit_line("static inline float _bitcast_i32_to_f32(i32 v) { union { i32 i; float f; } u; u.i = v; return u.f; }");
        self.emit_line("static inline i32 _bitcast_f32_to_i32(float v) { union { i32 i; float f; } u; u.f = v; return u.i; }");
        self.emit_line("");
    }

    // -----------------------------------------------------------------------
    // Phase 3: Extern declarations
    // -----------------------------------------------------------------------

    fn emit_extern_declarations(&mut self, modules: &[IrModule]) {
        self.emit_line("/* Runtime extern declarations */");

        for module in modules {
            for (_func_id, ext) in &module.extern_functions {
                if self.declared_externs.contains(&ext.name) {
                    continue;
                }
                self.declared_externs.insert(ext.name.clone());

                let ret_ty = Self::type_to_c(&ext.signature.return_type);
                let params: Vec<String> = ext
                    .signature
                    .parameters
                    .iter()
                    .filter(|p| p.ty != IrType::Void)
                    .map(|p| Self::type_to_c(&p.ty))
                    .collect();
                let params_str = if params.is_empty() {
                    "void".to_string()
                } else {
                    params.join(", ")
                };

                self.emit_line(&format!("extern {} {}({});", ret_ty, ext.name, params_str));
            }
        }
        self.emit_line("");
    }

    // -----------------------------------------------------------------------
    // Phase 4: Forward declarations
    // -----------------------------------------------------------------------

    fn emit_forward_declarations(&mut self, modules: &[IrModule]) {
        self.emit_line("/* Forward declarations */");

        for module in modules {
            for (func_id, function) in &module.functions {
                if function.cfg.blocks.is_empty() {
                    continue;
                }
                let c_name = match self.function_names.get(func_id) {
                    Some(n) => n.clone(),
                    None => continue,
                };
                let sig = self.build_c_signature(function, &c_name);
                self.emit_line(&format!("{};", sig));
            }
        }
        self.emit_line("");
    }

    // -----------------------------------------------------------------------
    // Phase 5: Function emission
    // -----------------------------------------------------------------------

    fn emit_function(
        &mut self,
        func_id: IrFunctionId,
        function: &crate::ir::IrFunction,
    ) -> Result<(), String> {
        let c_name = self
            .function_names
            .get(&func_id)
            .cloned()
            .unwrap_or_else(|| format!("fn_{}", func_id.0));

        let sig = self.build_c_signature(function, &c_name);
        self.emit_line(&format!("{} {{", sig));
        self.indent += 1;

        // Collect all registers used in this function
        let mut all_regs: BTreeMap<IrId, IrType> = BTreeMap::new();

        // From register_types map
        for (id, ty) in &function.register_types {
            all_regs.insert(*id, ty.clone());
        }

        // From phi nodes
        for block in function.cfg.blocks.values() {
            for phi in &block.phi_nodes {
                all_regs.entry(phi.dest).or_insert_with(|| phi.ty.clone());
            }
        }

        // Parameter registers (don't redeclare)
        let param_regs: HashSet<IrId> = function
            .signature
            .parameters
            .iter()
            .filter(|p| p.ty != IrType::Void)
            .map(|p| p.reg)
            .collect();

        // Declare local variables (skip parameters and void types)
        for (id, ty) in &all_regs {
            if param_regs.contains(id) {
                continue;
            }
            let c_type = Self::type_to_c(ty);
            if c_type == "void" {
                continue;
            }
            self.emit_line(&format!("{} r{} = 0;", c_type, id.as_u32()));
        }
        if !all_regs.is_empty() {
            self.emit_line("");
        }

        // Emit blocks in order (entry block first)
        let entry = function.cfg.entry_block;
        let mut block_order: Vec<IrBlockId> = Vec::new();
        block_order.push(entry);
        for block_id in function.cfg.blocks.keys() {
            if *block_id != entry {
                block_order.push(*block_id);
            }
        }

        // Collect phi info for predecessor insertion
        let phi_info = self.collect_phi_copies(function);

        for block_id in &block_order {
            let block = match function.cfg.blocks.get(block_id) {
                Some(b) => b,
                None => continue,
            };

            self.emit_line(&format!("bb{}:", block_id.as_u32()));
            self.indent += 1;

            // Emit instructions (phi nodes handled at predecessors)
            for inst in &block.instructions {
                self.emit_instruction(inst, function)?;
            }

            // Emit terminator with phi copies
            self.emit_terminator(&block.terminator, *block_id, &phi_info)?;

            self.indent -= 1;
        }

        self.indent -= 1;
        self.emit_line("}");
        self.emit_line("");

        Ok(())
    }

    /// Build C function signature string.
    fn build_c_signature(
        &self,
        function: &crate::ir::IrFunction,
        c_name: &str,
    ) -> String {
        let ret_ty = Self::type_to_c(&function.signature.return_type);
        let params: Vec<String> = function
            .signature
            .parameters
            .iter()
            .filter(|p| p.ty != IrType::Void)
            .map(|p| format!("{} r{}", Self::type_to_c(&p.ty), p.reg.as_u32()))
            .collect();
        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        format!("{} {}({})", ret_ty, c_name, params_str)
    }

    // -----------------------------------------------------------------------
    // Phi node lowering
    // -----------------------------------------------------------------------

    /// Collect phi copies: for each (predecessor, target_block), what assignments to make.
    fn collect_phi_copies(
        &self,
        function: &crate::ir::IrFunction,
    ) -> HashMap<(IrBlockId, IrBlockId), Vec<(IrId, IrId)>> {
        let mut copies: HashMap<(IrBlockId, IrBlockId), Vec<(IrId, IrId)>> = HashMap::new();

        for (block_id, block) in &function.cfg.blocks {
            for phi in &block.phi_nodes {
                for (pred_block, value) in &phi.incoming {
                    copies
                        .entry((*pred_block, *block_id))
                        .or_default()
                        .push((phi.dest, *value));
                }
            }
        }

        copies
    }

    /// Emit phi copies for a specific edge (pred_block → target_block).
    fn emit_phi_copies(
        &mut self,
        pred_block: IrBlockId,
        target_block: IrBlockId,
        phi_info: &HashMap<(IrBlockId, IrBlockId), Vec<(IrId, IrId)>>,
    ) {
        if let Some(copies) = phi_info.get(&(pred_block, target_block)) {
            if copies.len() == 1 {
                // Single phi — no parallel copy issue
                let (dest, src) = copies[0];
                self.emit_line(&format!("r{} = r{};", dest.as_u32(), src.as_u32()));
            } else if copies.len() > 1 {
                // Multiple phis — use temp variables for parallel copy
                self.emit_line("{");
                self.indent += 1;
                // First, capture all source values into temps
                for (i, (_dest, src)) in copies.iter().enumerate() {
                    self.emit_line(&format!(
                        "i64 _phi_t{} = (i64)r{};",
                        i,
                        src.as_u32()
                    ));
                }
                // Then assign all destinations
                for (i, (dest, _src)) in copies.iter().enumerate() {
                    self.emit_line(&format!("r{} = _phi_t{};", dest.as_u32(), i));
                }
                self.indent -= 1;
                self.emit_line("}");
            }
        }
    }

    // -----------------------------------------------------------------------
    // Instruction emission
    // -----------------------------------------------------------------------

    fn emit_instruction(
        &mut self,
        inst: &IrInstruction,
        function: &crate::ir::IrFunction,
    ) -> Result<(), String> {
        match inst {
            // === Value Operations ===
            IrInstruction::Const { dest, value } => {
                let val_str = Self::value_to_c(value);
                self.emit_line(&format!("r{} = {};", dest.as_u32(), val_str));
            }

            IrInstruction::Copy { dest, src }
            | IrInstruction::Move { dest, src }
            | IrInstruction::Clone { dest, src }
            | IrInstruction::BorrowImmutable { dest, src, .. }
            | IrInstruction::BorrowMutable { dest, src, .. } => {
                self.emit_line(&format!("r{} = r{};", dest.as_u32(), src.as_u32()));
            }

            IrInstruction::EndBorrow { .. } => {
                // No-op in C (lifetime tracking is compile-time only)
            }

            IrInstruction::Load { dest, ptr, ty } => {
                let c_type = Self::type_to_c(ty);
                let cast = if c_type == "void" {
                    "i64".to_string()
                } else {
                    c_type
                };
                self.emit_line(&format!(
                    "r{} = *({}*)(void*)r{};",
                    dest.as_u32(),
                    cast,
                    ptr.as_u32()
                ));
            }

            IrInstruction::Store { ptr, value } => {
                // Determine type from register_types of value
                let val_ty = function
                    .register_types
                    .get(value)
                    .cloned()
                    .unwrap_or(IrType::I64);
                let c_type = Self::type_to_c(&val_ty);
                let cast = if c_type == "void" { "i64" } else { &c_type };
                self.emit_line(&format!(
                    "*({}*)(void*)r{} = r{};",
                    cast,
                    ptr.as_u32(),
                    value.as_u32()
                ));
            }

            IrInstruction::LoadGlobal { dest, global_id, .. } => {
                self.emit_line(&format!(
                    "r{} = rayzor_global_load({});",
                    dest.as_u32(),
                    global_id.0
                ));
            }

            IrInstruction::StoreGlobal { global_id, value } => {
                self.emit_line(&format!(
                    "rayzor_global_store({}, r{});",
                    global_id.0,
                    value.as_u32()
                ));
            }

            // === Arithmetic ===
            IrInstruction::BinOp {
                dest,
                op,
                left,
                right,
            } => {
                let op_str = Self::binop_to_c(*op, left, right, function);
                self.emit_line(&format!(
                    "r{} = {};",
                    dest.as_u32(),
                    op_str
                ));
            }

            IrInstruction::UnOp { dest, op, operand } => {
                let expr = match op {
                    UnaryOp::Neg | UnaryOp::FNeg => format!("-r{}", operand.as_u32()),
                    UnaryOp::Not => format!("~r{}", operand.as_u32()),
                };
                self.emit_line(&format!("r{} = {};", dest.as_u32(), expr));
            }

            IrInstruction::Cmp {
                dest,
                op,
                left,
                right,
            } => {
                let expr = Self::cmpop_to_c(*op, left, right, function);
                self.emit_line(&format!("r{} = {};", dest.as_u32(), expr));
            }

            // === Memory ===
            IrInstruction::Alloc { dest, ty, count } => {
                let elem_size = Self::type_size(ty);
                if let Some(count_reg) = count {
                    self.emit_line(&format!(
                        "r{} = (i64)(intptr_t)rayzor_malloc((i64)(r{} * {}));",
                        dest.as_u32(),
                        count_reg.as_u32(),
                        elem_size
                    ));
                } else {
                    self.emit_line(&format!(
                        "r{} = (i64)(intptr_t)rayzor_malloc({});",
                        dest.as_u32(),
                        elem_size
                    ));
                }
            }

            IrInstruction::Free { ptr } => {
                self.emit_line(&format!(
                    "rayzor_tracked_free((void*)(intptr_t)r{});",
                    ptr.as_u32()
                ));
            }

            IrInstruction::GetElementPtr {
                dest,
                ptr,
                indices,
                ty,
            } => {
                // Determine element size: 8 for struct fields, 1 for byte pointers
                let elem_size = match ty {
                    IrType::Ptr(inner) => match inner.as_ref() {
                        IrType::U8 | IrType::I8 => 1,
                        _ => 8,
                    },
                    _ => 8,
                };
                if let Some(idx) = indices.first() {
                    if elem_size == 1 {
                        self.emit_line(&format!(
                            "r{} = (i64)((char*)(intptr_t)r{} + (i64)r{});",
                            dest.as_u32(),
                            ptr.as_u32(),
                            idx.as_u32()
                        ));
                    } else {
                        self.emit_line(&format!(
                            "r{} = (i64)((char*)(intptr_t)r{} + (i64)r{} * {});",
                            dest.as_u32(),
                            ptr.as_u32(),
                            idx.as_u32(),
                            elem_size
                        ));
                    }
                }
            }

            IrInstruction::PtrAdd {
                dest, ptr, offset, ..
            } => {
                self.emit_line(&format!(
                    "r{} = (i64)((char*)(intptr_t)r{} + (i64)r{});",
                    dest.as_u32(),
                    ptr.as_u32(),
                    offset.as_u32()
                ));
            }

            IrInstruction::MemCopy { dest, src, size } => {
                self.emit_line(&format!(
                    "memcpy((void*)(intptr_t)r{}, (void*)(intptr_t)r{}, (size_t)r{});",
                    dest.as_u32(),
                    src.as_u32(),
                    size.as_u32()
                ));
            }

            IrInstruction::MemSet { dest, value, size } => {
                self.emit_line(&format!(
                    "memset((void*)(intptr_t)r{}, (int)r{}, (size_t)r{});",
                    dest.as_u32(),
                    value.as_u32(),
                    size.as_u32()
                ));
            }

            // === Type Operations ===
            IrInstruction::Cast {
                dest,
                src,
                from_ty,
                to_ty,
            } => {
                self.emit_cast(*dest, *src, from_ty, to_ty);
            }

            IrInstruction::BitCast { dest, src, ty } => {
                let src_ty = function
                    .register_types
                    .get(src)
                    .cloned()
                    .unwrap_or(IrType::I64);
                self.emit_bitcast(*dest, *src, &src_ty, ty);
            }

            // === Function Calls ===
            IrInstruction::CallDirect {
                dest,
                func_id,
                args,
                ..
            } => {
                let c_name = self
                    .function_names
                    .get(func_id)
                    .cloned()
                    .unwrap_or_else(|| format!("fn_{}", func_id.0));

                let args_str: Vec<String> =
                    args.iter().map(|a| format!("r{}", a.as_u32())).collect();

                if let Some(d) = dest {
                    self.emit_line(&format!(
                        "r{} = {}({});",
                        d.as_u32(),
                        c_name,
                        args_str.join(", ")
                    ));
                } else {
                    self.emit_line(&format!("{}({});", c_name, args_str.join(", ")));
                }
            }

            IrInstruction::CallIndirect {
                dest,
                func_ptr,
                args,
                signature,
                ..
            } => {
                // Build function pointer type from signature
                let (ret_type, param_types) = match signature {
                    IrType::Function {
                        params,
                        return_type,
                        ..
                    } => {
                        let ret = Self::type_to_c(return_type);
                        let params: Vec<String> =
                            params.iter().map(|p| Self::type_to_c(p)).collect();
                        (ret, params)
                    }
                    _ => {
                        // Fallback: assume i64 return, i64 params
                        let params: Vec<String> =
                            args.iter().map(|_| "i64".to_string()).collect();
                        ("i64".to_string(), params)
                    }
                };
                let params_str = if param_types.is_empty() {
                    "void".to_string()
                } else {
                    param_types.join(", ")
                };
                let args_str: Vec<String> =
                    args.iter().map(|a| format!("r{}", a.as_u32())).collect();

                let cast = format!("({}(*)({}))r{}", ret_type, params_str, func_ptr.as_u32());
                if let Some(d) = dest {
                    self.emit_line(&format!(
                        "r{} = {}({});",
                        d.as_u32(),
                        cast,
                        args_str.join(", ")
                    ));
                } else {
                    self.emit_line(&format!("{}({});", cast, args_str.join(", ")));
                }
            }

            // === Closures ===
            IrInstruction::MakeClosure {
                dest,
                func_id,
                captured_values,
            } => {
                // Allocate 16-byte closure struct: [fn_ptr: i64, env_ptr: i64]
                self.emit_line(&format!(
                    "r{} = (i64)(intptr_t)rayzor_malloc(16);",
                    dest.as_u32()
                ));
                // Store function pointer at offset 0
                let fn_name = self
                    .function_names
                    .get(func_id)
                    .cloned()
                    .unwrap_or_else(|| format!("fn_{}", func_id.0));
                self.emit_line(&format!(
                    "*(i64*)(intptr_t)r{} = (i64)(intptr_t)&{};",
                    dest.as_u32(),
                    fn_name
                ));
                // Allocate and populate environment
                if !captured_values.is_empty() {
                    let env_size = captured_values.len() * 8;
                    self.emit_line(&format!(
                        "{{ void* _env = rayzor_malloc({}); ",
                        env_size
                    ));
                    for (i, cap) in captured_values.iter().enumerate() {
                        self.emit_line(&format!(
                            "  ((i64*)_env)[{}] = (i64)r{};",
                            i,
                            cap.as_u32()
                        ));
                    }
                    self.emit_line(&format!(
                        "  *(i64*)((char*)(intptr_t)r{} + 8) = (i64)(intptr_t)_env; }}",
                        dest.as_u32()
                    ));
                } else {
                    self.emit_line(&format!(
                        "*(i64*)((char*)(intptr_t)r{} + 8) = 0;",
                        dest.as_u32()
                    ));
                }
            }

            IrInstruction::ClosureFunc { dest, closure } => {
                self.emit_line(&format!(
                    "r{} = *(i64*)(intptr_t)r{};",
                    dest.as_u32(),
                    closure.as_u32()
                ));
            }

            IrInstruction::ClosureEnv { dest, closure } => {
                self.emit_line(&format!(
                    "r{} = *(i64*)((char*)(intptr_t)r{} + 8);",
                    dest.as_u32(),
                    closure.as_u32()
                ));
            }

            // === Select ===
            IrInstruction::Select {
                dest,
                condition,
                true_val,
                false_val,
            } => {
                self.emit_line(&format!(
                    "r{} = r{} ? r{} : r{};",
                    dest.as_u32(),
                    condition.as_u32(),
                    true_val.as_u32(),
                    false_val.as_u32()
                ));
            }

            // === Aggregate Operations ===
            IrInstruction::ExtractValue {
                dest,
                aggregate,
                indices,
            } => {
                if let Some(&idx) = indices.first() {
                    self.emit_line(&format!(
                        "r{} = ((i64*)(intptr_t)r{})[{}];",
                        dest.as_u32(),
                        aggregate.as_u32(),
                        idx
                    ));
                }
            }

            IrInstruction::InsertValue {
                dest,
                aggregate,
                value,
                indices,
            } => {
                // Copy aggregate then set field
                self.emit_line(&format!(
                    "r{} = r{};",
                    dest.as_u32(),
                    aggregate.as_u32()
                ));
                if let Some(&idx) = indices.first() {
                    self.emit_line(&format!(
                        "((i64*)(intptr_t)r{})[{}] = (i64)r{};",
                        dest.as_u32(),
                        idx,
                        value.as_u32()
                    ));
                }
            }

            // === Union/Enum Operations ===
            IrInstruction::CreateUnion {
                dest,
                discriminant,
                value,
                ..
            } => {
                // Allocate tag + value (16 bytes minimum)
                self.emit_line(&format!(
                    "r{} = (i64)(intptr_t)rayzor_malloc(16);",
                    dest.as_u32()
                ));
                self.emit_line(&format!(
                    "*(i64*)(intptr_t)r{} = {};",
                    dest.as_u32(),
                    discriminant
                ));
                self.emit_line(&format!(
                    "*(i64*)((char*)(intptr_t)r{} + 8) = (i64)r{};",
                    dest.as_u32(),
                    value.as_u32()
                ));
            }

            IrInstruction::ExtractDiscriminant { dest, union_val } => {
                self.emit_line(&format!(
                    "r{} = *(i64*)(intptr_t)r{};",
                    dest.as_u32(),
                    union_val.as_u32()
                ));
            }

            IrInstruction::ExtractUnionValue {
                dest, union_val, ..
            } => {
                self.emit_line(&format!(
                    "r{} = *(i64*)((char*)(intptr_t)r{} + 8);",
                    dest.as_u32(),
                    union_val.as_u32()
                ));
            }

            // === Struct Operations ===
            IrInstruction::CreateStruct { dest, fields, .. } => {
                let size = fields.len() * 8;
                self.emit_line(&format!(
                    "r{} = (i64)(intptr_t)rayzor_malloc({});",
                    dest.as_u32(),
                    size.max(8)
                ));
                for (i, f) in fields.iter().enumerate() {
                    self.emit_line(&format!(
                        "((i64*)(intptr_t)r{})[{}] = (i64)r{};",
                        dest.as_u32(),
                        i,
                        f.as_u32()
                    ));
                }
            }

            // === Special Values ===
            IrInstruction::Undef { dest, .. } => {
                self.emit_line(&format!("r{} = 0;", dest.as_u32()));
            }

            IrInstruction::FunctionRef { dest, func_id } => {
                let fn_name = self
                    .function_names
                    .get(func_id)
                    .cloned()
                    .unwrap_or_else(|| format!("fn_{}", func_id.0));
                self.emit_line(&format!(
                    "r{} = (i64)(intptr_t)&{};",
                    dest.as_u32(),
                    fn_name
                ));
            }

            IrInstruction::Panic { message } => {
                if let Some(msg) = message {
                    let escaped = msg.replace('\\', "\\\\").replace('"', "\\\"");
                    self.emit_line(&format!(
                        "{{ extern void abort(void); fprintf(stderr, \"PANIC: {}\\n\"); abort(); }}",
                        escaped
                    ));
                } else {
                    self.emit_line("{ extern void abort(void); abort(); }");
                }
            }

            // === Exception Handling ===
            IrInstruction::Throw { exception } => {
                self.emit_line(&format!(
                    "rayzor_throw((i64)r{});",
                    exception.as_u32()
                ));
            }

            IrInstruction::LandingPad { dest, .. } => {
                // Landing pads are handled by the runtime setjmp/longjmp mechanism
                self.emit_line(&format!("r{} = 0; /* landing pad */", dest.as_u32()));
            }

            IrInstruction::Resume { exception } => {
                self.emit_line(&format!(
                    "rayzor_throw((i64)r{}); /* resume */",
                    exception.as_u32()
                ));
            }

            // === Debug (no-ops in C) ===
            IrInstruction::DebugLoc { .. } => {}

            IrInstruction::InlineAsm { dest, .. } => {
                // Can't emit inline asm in portable C; emit a no-op
                if let Some(d) = dest {
                    self.emit_line(&format!("r{} = 0; /* inline asm stub */", d.as_u32()));
                }
            }

            // === Phi (handled at predecessor blocks, not here) ===
            IrInstruction::Phi { .. } => {}

            // === Legacy control flow in instructions (should be in terminators) ===
            IrInstruction::Jump { .. }
            | IrInstruction::Branch { .. }
            | IrInstruction::Switch { .. }
            | IrInstruction::Return { .. } => {}

            // === SIMD Vector Operations (scalar fallback) ===
            IrInstruction::VectorLoad { dest, ptr, vec_ty } => {
                let count = Self::vector_count(vec_ty);
                let elem_size = Self::vector_elem_size(vec_ty);
                self.emit_line(&format!(
                    "memcpy(&r{}, (void*)(intptr_t)r{}, {});",
                    dest.as_u32(),
                    ptr.as_u32(),
                    count * elem_size
                ));
            }

            IrInstruction::VectorStore { ptr, value, vec_ty } => {
                let count = Self::vector_count(vec_ty);
                let elem_size = Self::vector_elem_size(vec_ty);
                self.emit_line(&format!(
                    "memcpy((void*)(intptr_t)r{}, &r{}, {});",
                    ptr.as_u32(),
                    value.as_u32(),
                    count * elem_size
                ));
            }

            IrInstruction::VectorBinOp { dest, op, left, right, vec_ty } => {
                let count = Self::vector_count(vec_ty);
                let elem_type = Self::vector_elem_c_type(vec_ty);
                let op_char = Self::simple_binop_char(*op);
                self.emit_line(&format!(
                    "for (int _vi=0; _vi<{}; _vi++) (({elem_type}*)&r{})[_vi] = (({elem_type}*)&r{})[_vi] {op_char} (({elem_type}*)&r{})[_vi];",
                    count, dest.as_u32(), left.as_u32(), right.as_u32()
                ));
            }

            IrInstruction::VectorSplat { dest, scalar, vec_ty } => {
                let count = Self::vector_count(vec_ty);
                let elem_type = Self::vector_elem_c_type(vec_ty);
                self.emit_line(&format!(
                    "for (int _vi=0; _vi<{}; _vi++) (({elem_type}*)&r{})[_vi] = ({elem_type})r{};",
                    count, dest.as_u32(), scalar.as_u32()
                ));
            }

            IrInstruction::VectorExtract { dest, vector, index } => {
                self.emit_line(&format!(
                    "r{} = ((i64*)&r{})[{}];",
                    dest.as_u32(),
                    vector.as_u32(),
                    index
                ));
            }

            IrInstruction::VectorInsert { dest, vector, scalar, index } => {
                self.emit_line(&format!("r{} = r{};", dest.as_u32(), vector.as_u32()));
                self.emit_line(&format!(
                    "((i64*)&r{})[{}] = (i64)r{};",
                    dest.as_u32(),
                    index,
                    scalar.as_u32()
                ));
            }

            IrInstruction::VectorReduce { dest, op, vector } => {
                // Simple reduction: accumulate across elements
                let op_char = Self::simple_binop_char(*op);
                self.emit_line(&format!(
                    "r{} = ((i64*)&r{})[0]; for (int _vi=1; _vi<4; _vi++) r{} = r{} {op_char} ((i64*)&r{})[_vi];",
                    dest.as_u32(), vector.as_u32(), dest.as_u32(), dest.as_u32(), vector.as_u32()
                ));
            }

            IrInstruction::VectorUnaryOp { dest, op, operand, vec_ty } => {
                let count = Self::vector_count(vec_ty);
                let elem_type = Self::vector_elem_c_type(vec_ty);
                let fn_name = match op {
                    crate::ir::instructions::VectorUnaryOpKind::Sqrt => "sqrt",
                    crate::ir::instructions::VectorUnaryOpKind::Abs => "fabs",
                    crate::ir::instructions::VectorUnaryOpKind::Neg => "-",
                    crate::ir::instructions::VectorUnaryOpKind::Ceil => "ceil",
                    crate::ir::instructions::VectorUnaryOpKind::Floor => "floor",
                    crate::ir::instructions::VectorUnaryOpKind::Trunc => "trunc",
                    crate::ir::instructions::VectorUnaryOpKind::Round => "round",
                };
                if matches!(op, crate::ir::instructions::VectorUnaryOpKind::Neg) {
                    self.emit_line(&format!(
                        "for (int _vi=0; _vi<{}; _vi++) (({elem_type}*)&r{})[_vi] = -(({elem_type}*)&r{})[_vi];",
                        count, dest.as_u32(), operand.as_u32()
                    ));
                } else {
                    self.emit_line(&format!(
                        "for (int _vi=0; _vi<{}; _vi++) (({elem_type}*)&r{})[_vi] = ({elem_type}){}((double)(({elem_type}*)&r{})[_vi]);",
                        count, dest.as_u32(), fn_name, operand.as_u32()
                    ));
                }
            }

            IrInstruction::VectorMinMax { dest, op, left, right, vec_ty } => {
                let count = Self::vector_count(vec_ty);
                let elem_type = Self::vector_elem_c_type(vec_ty);
                let cmp = match op {
                    crate::ir::instructions::VectorMinMaxKind::Min => "<",
                    crate::ir::instructions::VectorMinMaxKind::Max => ">",
                };
                self.emit_line(&format!(
                    "for (int _vi=0; _vi<{}; _vi++) {{ {elem_type} _a=(({elem_type}*)&r{})[_vi], _b=(({elem_type}*)&r{})[_vi]; (({elem_type}*)&r{})[_vi] = _a {cmp} _b ? _a : _b; }}",
                    count, left.as_u32(), right.as_u32(), dest.as_u32()
                ));
            }
        }

        Ok(())
    }

    // -----------------------------------------------------------------------
    // Terminator emission
    // -----------------------------------------------------------------------

    fn emit_terminator(
        &mut self,
        term: &IrTerminator,
        current_block: IrBlockId,
        phi_info: &HashMap<(IrBlockId, IrBlockId), Vec<(IrId, IrId)>>,
    ) -> Result<(), String> {
        match term {
            IrTerminator::Branch { target } => {
                self.emit_phi_copies(current_block, *target, phi_info);
                self.emit_line(&format!("goto bb{};", target.as_u32()));
            }

            IrTerminator::CondBranch {
                condition,
                true_target,
                false_target,
            } => {
                // Emit phi copies for true branch
                let has_true_phis =
                    phi_info.contains_key(&(current_block, *true_target));
                let has_false_phis =
                    phi_info.contains_key(&(current_block, *false_target));

                if !has_true_phis && !has_false_phis {
                    self.emit_line(&format!(
                        "if (r{}) goto bb{}; else goto bb{};",
                        condition.as_u32(),
                        true_target.as_u32(),
                        false_target.as_u32()
                    ));
                } else {
                    self.emit_line(&format!("if (r{}) {{", condition.as_u32()));
                    self.indent += 1;
                    self.emit_phi_copies(current_block, *true_target, phi_info);
                    self.emit_line(&format!("goto bb{};", true_target.as_u32()));
                    self.indent -= 1;
                    self.emit_line("} else {");
                    self.indent += 1;
                    self.emit_phi_copies(current_block, *false_target, phi_info);
                    self.emit_line(&format!("goto bb{};", false_target.as_u32()));
                    self.indent -= 1;
                    self.emit_line("}");
                }
            }

            IrTerminator::Switch {
                value,
                cases,
                default,
            } => {
                self.emit_line(&format!("switch ((i64)r{}) {{", value.as_u32()));
                self.indent += 1;
                for (val, target) in cases {
                    self.emit_line(&format!("case {}:", val));
                    self.indent += 1;
                    self.emit_phi_copies(current_block, *target, phi_info);
                    self.emit_line(&format!("goto bb{};", target.as_u32()));
                    self.indent -= 1;
                }
                self.emit_line("default:");
                self.indent += 1;
                self.emit_phi_copies(current_block, *default, phi_info);
                self.emit_line(&format!("goto bb{};", default.as_u32()));
                self.indent -= 1;
                self.indent -= 1;
                self.emit_line("}");
            }

            IrTerminator::Return { value } => {
                if let Some(v) = value {
                    self.emit_line(&format!("return r{};", v.as_u32()));
                } else {
                    self.emit_line("return;");
                }
            }

            IrTerminator::Unreachable => {
                self.emit_line("__builtin_unreachable();");
            }

            IrTerminator::NoReturn { .. } => {
                self.emit_line("__builtin_unreachable();");
            }
        }

        Ok(())
    }

    // -----------------------------------------------------------------------
    // Phase 6: Main wrapper
    // -----------------------------------------------------------------------

    fn emit_main_wrapper(&mut self, entry_func: &str, startup_funcs: &[String]) {
        self.emit_line("/* Entry point */");
        self.emit_line("extern void rayzor_init_args_from_argv(int, char**);");
        self.emit_line("");
        self.emit_line("int main(int argc, char** argv) {");
        self.indent += 1;
        self.emit_line("rayzor_init_args_from_argv(argc, argv);");

        // Call startup functions by looking up their C names
        for func in startup_funcs {
            // Find by original function name in the name map
            let found = self
                .function_names
                .values()
                .find(|n| n.contains(&Self::sanitize_name(func)));
            if let Some(c_name) = found {
                self.emit_line(&format!("{}();", c_name));
            }
        }

        // Call entry function — if it was "main", it's been renamed to "_haxe_main"
        let entry_c_name = if entry_func == "main" {
            "_haxe_main".to_string()
        } else {
            Self::sanitize_name(entry_func)
        };
        // Find the actual C name in our map
        let found = self
            .function_names
            .values()
            .find(|n| **n == entry_c_name);
        if let Some(c_name) = found {
            self.emit_line(&format!("{}();", c_name));
        } else {
            self.emit_line(&format!("{}();", entry_c_name));
        }

        self.emit_line("return 0;");
        self.indent -= 1;
        self.emit_line("}");
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    fn emit_line(&mut self, line: &str) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(line);
        self.output.push('\n');
    }

    fn type_to_c(ty: &IrType) -> String {
        match ty {
            IrType::Void => "void".to_string(),
            IrType::Bool => "i8".to_string(),
            IrType::I8 => "i8".to_string(),
            IrType::I16 => "i16".to_string(),
            IrType::I32 => "i32".to_string(),
            IrType::I64 => "i64".to_string(),
            IrType::U8 => "u8".to_string(),
            IrType::U16 => "u16".to_string(),
            IrType::U32 => "u32".to_string(),
            IrType::U64 => "u64".to_string(),
            IrType::F32 => "float".to_string(),
            IrType::F64 => "double".to_string(),
            IrType::Ptr(_) | IrType::Ref(_) => "i64".to_string(), // pointers as i64
            IrType::String => "i64".to_string(),
            IrType::Any => "i64".to_string(),
            IrType::Function { .. } => "i64".to_string(), // fn ptrs as i64
            IrType::Array(_, _) => "i64".to_string(),
            IrType::Slice(_) => "i64".to_string(),
            IrType::Struct { .. } => "i64".to_string(),
            IrType::Union { .. } => "i64".to_string(),
            IrType::Vector { .. } => "i64".to_string(), // scalar fallback
            IrType::TypeVar(_) => "i64".to_string(),
            IrType::Generic { .. } => "i64".to_string(),
            IrType::Opaque { .. } => "i64".to_string(),
        }
    }

    fn type_size(ty: &IrType) -> usize {
        match ty {
            IrType::Void => 0,
            IrType::Bool | IrType::I8 | IrType::U8 => 1,
            IrType::I16 | IrType::U16 => 2,
            IrType::I32 | IrType::U32 | IrType::F32 => 4,
            IrType::I64 | IrType::U64 | IrType::F64 => 8,
            IrType::Ptr(_) | IrType::Ref(_) | IrType::String | IrType::Any => 8,
            IrType::Function { .. } => 8,
            IrType::Struct { fields, .. } => fields.len() * 8,
            _ => 8,
        }
    }

    fn value_to_c(value: &IrValue) -> String {
        match value {
            IrValue::Void => "0".to_string(),
            IrValue::Undef => "0".to_string(),
            IrValue::Null => "0".to_string(),
            IrValue::Bool(b) => if *b { "1" } else { "0" }.to_string(),
            IrValue::I8(v) => format!("(i8){}", v),
            IrValue::I16(v) => format!("(i16){}", v),
            IrValue::I32(v) => format!("{}",  v),
            IrValue::I64(v) => format!("{}LL", v),
            IrValue::U8(v) => format!("(u8){}", v),
            IrValue::U16(v) => format!("(u16){}", v),
            IrValue::U32(v) => format!("{}u", v),
            IrValue::U64(v) => format!("{}ULL", v),
            IrValue::F32(v) => {
                if v.is_nan() {
                    "(float)(0.0/0.0)".to_string()
                } else if v.is_infinite() {
                    if *v > 0.0 { "(float)(1.0/0.0)".to_string() } else { "(float)(-1.0/0.0)".to_string() }
                } else {
                    format!("{}f", v)
                }
            }
            IrValue::F64(v) => {
                if v.is_nan() {
                    "(0.0/0.0)".to_string()
                } else if v.is_infinite() {
                    if *v > 0.0 { "(1.0/0.0)".to_string() } else { "(-1.0/0.0)".to_string() }
                } else {
                    format!("{}", v)
                }
            }
            IrValue::String(s) => {
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
                format!("(i64)(intptr_t)\"{}\"", escaped)
            }
            IrValue::Array(elems) => {
                // Not common in practice; emit 0
                format!("0 /* array({}) */", elems.len())
            }
            IrValue::Struct(fields) => {
                format!("0 /* struct({}) */", fields.len())
            }
            IrValue::Function(id) => format!("(i64)(intptr_t)0 /* fn_{} */", id.0),
            IrValue::Closure { .. } => "0 /* closure */".to_string(),
        }
    }

    fn binop_to_c(
        op: BinaryOp,
        left: &IrId,
        right: &IrId,
        _function: &crate::ir::IrFunction,
    ) -> String {
        let l = format!("r{}", left.as_u32());
        let r = format!("r{}", right.as_u32());
        match op {
            BinaryOp::Add | BinaryOp::FAdd => format!("{l} + {r}"),
            BinaryOp::Sub | BinaryOp::FSub => format!("{l} - {r}"),
            BinaryOp::Mul | BinaryOp::FMul => format!("{l} * {r}"),
            BinaryOp::Div | BinaryOp::FDiv => format!("{l} / {r}"),
            BinaryOp::Rem | BinaryOp::FRem => format!("{l} % {r}"),
            BinaryOp::And => format!("{l} & {r}"),
            BinaryOp::Or => format!("{l} | {r}"),
            BinaryOp::Xor => format!("{l} ^ {r}"),
            BinaryOp::Shl => format!("{l} << {r}"),
            BinaryOp::Shr => format!("{l} >> {r}"),
            BinaryOp::Ushr => format!("(i64)((u64){l} >> {r})"),
        }
    }

    fn cmpop_to_c(
        op: CompareOp,
        left: &IrId,
        right: &IrId,
        _function: &crate::ir::IrFunction,
    ) -> String {
        let l = format!("r{}", left.as_u32());
        let r = format!("r{}", right.as_u32());
        match op {
            CompareOp::Eq | CompareOp::FEq => format!("({l} == {r})"),
            CompareOp::Ne | CompareOp::FNe => format!("({l} != {r})"),
            CompareOp::Lt | CompareOp::FLt => format!("({l} < {r})"),
            CompareOp::Le | CompareOp::FLe => format!("({l} <= {r})"),
            CompareOp::Gt | CompareOp::FGt => format!("({l} > {r})"),
            CompareOp::Ge | CompareOp::FGe => format!("({l} >= {r})"),
            CompareOp::ULt => format!("((u64){l} < (u64){r})"),
            CompareOp::ULe => format!("((u64){l} <= (u64){r})"),
            CompareOp::UGt => format!("((u64){l} > (u64){r})"),
            CompareOp::UGe => format!("((u64){l} >= (u64){r})"),
            CompareOp::FOrd => format!("({l} == {l} && {r} == {r})"), // neither is NaN
            CompareOp::FUno => format!("({l} != {l} || {r} != {r})"), // at least one NaN
        }
    }

    fn emit_cast(&mut self, dest: IrId, src: IrId, from_ty: &IrType, to_ty: &IrType) {
        let target_c = Self::type_to_c(to_ty);
        // Handle pointer ↔ integer conversions
        match (from_ty, to_ty) {
            (IrType::Ptr(_) | IrType::Ref(_), IrType::I64 | IrType::U64) => {
                self.emit_line(&format!(
                    "r{} = (i64)(intptr_t)r{};",
                    dest.as_u32(),
                    src.as_u32()
                ));
            }
            (IrType::I64 | IrType::U64, IrType::Ptr(_) | IrType::Ref(_)) => {
                self.emit_line(&format!(
                    "r{} = (i64)r{};",
                    dest.as_u32(),
                    src.as_u32()
                ));
            }
            _ => {
                self.emit_line(&format!(
                    "r{} = ({})r{};",
                    dest.as_u32(),
                    target_c,
                    src.as_u32()
                ));
            }
        }
    }

    fn emit_bitcast(&mut self, dest: IrId, src: IrId, from_ty: &IrType, to_ty: &IrType) {
        match (from_ty, to_ty) {
            (IrType::I64, IrType::F64) => {
                self.emit_line(&format!(
                    "r{} = _bitcast_i64_to_f64(r{});",
                    dest.as_u32(),
                    src.as_u32()
                ));
            }
            (IrType::F64, IrType::I64) => {
                self.emit_line(&format!(
                    "r{} = _bitcast_f64_to_i64(r{});",
                    dest.as_u32(),
                    src.as_u32()
                ));
            }
            (IrType::I32, IrType::F32) => {
                self.emit_line(&format!(
                    "r{} = _bitcast_i32_to_f32(r{});",
                    dest.as_u32(),
                    src.as_u32()
                ));
            }
            (IrType::F32, IrType::I32) => {
                self.emit_line(&format!(
                    "r{} = _bitcast_f32_to_i32(r{});",
                    dest.as_u32(),
                    src.as_u32()
                ));
            }
            _ => {
                // Generic: just assign (same size types)
                self.emit_line(&format!("r{} = r{};", dest.as_u32(), src.as_u32()));
            }
        }
    }

    fn simple_binop_char(op: BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add | BinaryOp::FAdd => "+",
            BinaryOp::Sub | BinaryOp::FSub => "-",
            BinaryOp::Mul | BinaryOp::FMul => "*",
            BinaryOp::Div | BinaryOp::FDiv => "/",
            BinaryOp::Rem | BinaryOp::FRem => "%",
            BinaryOp::And => "&",
            BinaryOp::Or => "|",
            BinaryOp::Xor => "^",
            BinaryOp::Shl => "<<",
            BinaryOp::Shr | BinaryOp::Ushr => ">>",
        }
    }

    fn vector_count(ty: &IrType) -> usize {
        match ty {
            IrType::Vector { count, .. } => *count,
            _ => 4, // default
        }
    }

    fn vector_elem_size(ty: &IrType) -> usize {
        match ty {
            IrType::Vector { element, .. } => Self::type_size(element),
            _ => 4,
        }
    }

    fn vector_elem_c_type(ty: &IrType) -> &'static str {
        match ty {
            IrType::Vector { element, .. } => match element.as_ref() {
                IrType::F32 => "float",
                IrType::F64 => "double",
                IrType::I32 => "i32",
                IrType::I64 => "i64",
                _ => "i32",
            },
            _ => "float",
        }
    }
}
