//! WASM Bindgen — generates JS/TS wrapper classes from Haxe class definitions.
//!
//! Produces TypeScript type definitions and JavaScript wrapper classes that
//! call into WASM-exported functions with proper type marshaling.
//! Similar to wasm-bindgen but for Haxe → WASM.
//!
//! Usage: `rayzor build --target wasm --browser --bindgen`
//!
//! Input: MIR module with exported functions
//! Output: `.d.ts` type definitions + `.js` wrapper module

use crate::ir::modules::IrModule;
use crate::ir::IrType;

/// Generate TypeScript definitions for exported WASM functions.
pub fn generate_typescript_defs(modules: &[&IrModule]) -> String {
    let mut ts = String::new();
    ts.push_str("// Auto-generated by rayzor build --target wasm\n");
    ts.push_str("// TypeScript definitions for WASM exports\n\n");

    ts.push_str("export interface RayzorWasm {\n");
    ts.push_str("  /** Initialize the WASM module (calls _start) */\n");
    ts.push_str("  init(): Promise<void>;\n\n");

    for module in modules {
        for func in module.functions.values() {
            // Export functions with "export_" prefix or public static functions
            if !func.name.starts_with("export_") {
                continue;
            }

            let export_name = &func.name["export_".len()..];
            let params: Vec<String> = func
                .signature
                .parameters
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, ir_type_to_ts(&p.ty)))
                .collect();
            let ret = ir_type_to_ts(&func.signature.return_type);

            ts.push_str(&format!(
                "  /** {} */\n  {}({}): {};\n\n",
                export_name,
                export_name,
                params.join(", "),
                ret
            ));
        }
    }

    ts.push_str("}\n\n");
    ts.push_str("export function loadRayzor(wasmPath: string): Promise<RayzorWasm>;\n");
    ts
}

/// Generate JavaScript wrapper module for exported WASM functions.
pub fn generate_js_bindings(modules: &[&IrModule], wasm_filename: &str) -> String {
    let mut js = String::new();
    js.push_str("// Auto-generated by rayzor build --target wasm\n");
    js.push_str("// JavaScript bindings for WASM exports\n\n");

    // Import the harness
    js.push_str(&format!(
        "import {{ run as __initWasm }} from './{}';\n\n",
        wasm_filename.replace(".wasm", ".js")
    ));

    js.push_str("let __instance = null;\n");
    js.push_str("let __memory = null;\n\n");

    // String helper
    js.push_str(r#"
function readString(ptr) {
  if (!__memory || ptr === 0) return "";
  const view = new DataView(__memory.buffer);
  const dataPtr = view.getUint32(ptr, true);
  const len = view.getUint32(ptr + 4, true);
  if (dataPtr === 0 || len === 0) return "";
  const bytes = new Uint8Array(__memory.buffer, dataPtr, len);
  return new TextDecoder().decode(bytes);
}

function writeString(str) {
  if (!__memory) return 0;
  const encoded = new TextEncoder().encode(str);
  // Allocate via WASM malloc
  const dataPtr = __instance.exports.rayzor_malloc?.(encoded.length + 1) ?? 0;
  if (dataPtr === 0) return 0;
  new Uint8Array(__memory.buffer).set(encoded, dataPtr);
  new Uint8Array(__memory.buffer)[dataPtr + encoded.length] = 0;
  // Allocate HaxeString struct
  const hsPtr = __instance.exports.rayzor_malloc?.(12) ?? 0;
  if (hsPtr === 0) return 0;
  const view = new DataView(__memory.buffer);
  view.setUint32(hsPtr, dataPtr, true);
  view.setUint32(hsPtr + 4, encoded.length, true);
  view.setUint32(hsPtr + 8, encoded.length, true);
  return hsPtr;
}

"#);

    // Load function
    js.push_str(&format!(r#"
export async function loadRayzor(wasmPath) {{
  const isNode = typeof process !== "undefined" && process.versions?.node;
  let wasmBytes;
  if (isNode) {{
    const fs = await import("fs");
    wasmBytes = fs.readFileSync(wasmPath || "{}");
  }} else {{
    const resp = await fetch(wasmPath || "{}");
    wasmBytes = await resp.arrayBuffer();
  }}

  // Minimal WASI polyfill
  const wasi = {{
    fd_write: (fd, iovs, iovs_len, nwritten) => {{
      if (!__memory) return 0;
      const view = new DataView(__memory.buffer);
      let written = 0;
      for (let i = 0; i < iovs_len; i++) {{
        const ptr = view.getUint32(iovs + i * 8, true);
        const len = view.getUint32(iovs + i * 8 + 4, true);
        if (len > 0 && ptr + len <= __memory.buffer.byteLength) {{
          const bytes = new Uint8Array(__memory.buffer, ptr, len);
          if (isNode) process.stdout.write(Buffer.from(bytes));
          else console.log(new TextDecoder().decode(bytes));
          written += len;
        }}
      }}
      if (nwritten + 4 <= __memory.buffer.byteLength)
        view.setUint32(nwritten, written, true);
      return 0;
    }},
    environ_get: () => 0,
    environ_sizes_get: (c, b) => {{
      if (__memory) {{
        const v = new DataView(__memory.buffer);
        v.setUint32(c, 0, true);
        v.setUint32(b, 0, true);
      }}
      return 0;
    }},
    proc_exit: (code) => {{ if (isNode) process.exit(code); }},
  }};

  const {{ instance }} = await WebAssembly.instantiate(wasmBytes, {{
    wasi_snapshot_preview1: wasi,
  }});

  __instance = instance;
  __memory = instance.exports.memory;

  // Call _start to initialize
  if (instance.exports._start) {{
    instance.exports._start();
  }}

  return {{
    init: async () => {{}},
    _instance: instance,
    _memory: __memory,
    readString,
    writeString,
"#, wasm_filename, wasm_filename));

    // Generate wrapper methods for exported functions
    for module in modules {
        for func in module.functions.values() {
            if !func.name.starts_with("export_") {
                continue;
            }
            let export_name = &func.name["export_".len()..];
            let params: Vec<String> = func
                .signature
                .parameters
                .iter()
                .enumerate()
                .map(|(i, _)| format!("arg{}", i))
                .collect();

            js.push_str(&format!(
                "    {name}: ({params}) => instance.exports.{name}({params}),\n",
                name = export_name,
                params = params.join(", ")
            ));
        }
    }

    js.push_str("  };\n}\n");
    js
}

fn ir_type_to_ts(ty: &IrType) -> &'static str {
    match ty {
        IrType::Void => "void",
        IrType::Bool => "boolean",
        IrType::I8 | IrType::I16 | IrType::I32 | IrType::U8 | IrType::U16 | IrType::U32
        | IrType::I64 | IrType::U64 => "number",
        IrType::F32 | IrType::F64 => "number",
        IrType::String => "string",
        IrType::Ptr(_) => "number", // raw pointer
        _ => "any",
    }
}
