[project]
name = "socket-smoke"
entry = "Main.hx"

[build]
class-paths = [".", "../../"]

[tier]
interpreter_threshold = 1
warm_threshold = 30
hot_threshold = 5
blazing_threshold = "max"
sample_rate = 1
start_interpreted = false
enable_tier_promotion = false
verbosity = 0
enable_stack_traces = false
auto_upgrade_to_llvm_after_main_entry = false
