package rayzor.gpu;

/**
 * Auto-derived vertex buffer layout from @:gpuStruct classes.
 *
 * Parses the compile-time layout string generated by the compiler's
 * `gpuVertexLayout()` synthetic method.
 *
 * Example:
 * ```haxe
 * @:gpuStruct
 * class Vertex {
 *     public var x:Float;  // Float32 → location(0)
 *     public var y:Float;  // Float32 → location(1)
 *     public var z:Float;  // Float32 → location(2)
 *     public var r:Float;  // Float32 → location(3)
 *     public var g:Float;  // Float32 → location(4)
 *     public var b:Float;  // Float32 → location(5)
 * }
 *
 * var layout = VertexLayout.fromGpuStruct(Vertex.gpuVertexLayout());
 * // layout.stride == 24
 * // layout.attributes == [{format:0, offset:0, location:0}, ...]
 * ```
 */
class VertexLayout {
    /** Byte stride between consecutive vertices. */
    public var stride:Int;

    /** Vertex attributes in order. */
    public var attributes:Array<VertexAttr>;

    public function new() {
        stride = 0;
        attributes = [];
    }

    /**
     * Parse a layout from the compiler's gpuVertexLayout() encoded string.
     * Format: "stride;offset,format,location;offset,format,location;..."
     */
    public static function fromGpuStruct(encoded:String):VertexLayout {
        var layout = new VertexLayout();
        var parts = encoded.split(";");
        if (parts.length == 0) return layout;

        layout.stride = Std.parseInt(parts[0]);

        var i = 1;
        while (i < parts.length) {
            var fields = parts[i].split(",");
            if (fields.length >= 3) {
                layout.attributes.push({
                    offset: Std.parseInt(fields[0]),
                    format: Std.parseInt(fields[1]),
                    location: Std.parseInt(fields[2]),
                });
            }
            i++;
        }

        return layout;
    }

    /** Get the number of attributes. */
    public function attributeCount():Int {
        return attributes.length;
    }
}

/** A single vertex attribute descriptor. */
typedef VertexAttr = {
    /** Byte offset within the vertex. */
    offset:Int,
    /** VertexFormat enum index (0=Float32, 1=Float32x2, 2=Float32x3, 3=Float32x4, 4=Sint32, 5=Uint32). */
    format:Int,
    /** Shader location index (@location(N) in WGSL). */
    location:Int,
};
