// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class AccelerationStructureFlag {
	public static inline var ALLOW_UPDATE:Int = 1;
	public static inline var ALLOW_COMPACTION:Int = 2;
	public static inline var PREFER_FAST_TRACE:Int = 4;
	public static inline var PREFER_FAST_BUILD:Int = 8;
	public static inline var LOW_MEMORY:Int = 16;
	public static inline var USE_TRANSFORM:Int = 32;
	public static inline var ALLOW_RAY_HIT_VERTEX_RETURN:Int = 64;
}
