// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class AccelerationStructureGeometryFlag {
	public static inline var OPAQUE:Int = 1;
	public static inline var NO_DUPLICATE_ANY_HIT_INVOCATION:Int = 2;
}
