// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract AddressMode(Int) from Int to Int {
	var ClampToEdge = 0;
	var Repeat = 1;
	var MirrorRepeat = 2;
	var ClampToBorder = 3;
}
