// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract AlphaMode(Int) from Int to Int {
	var Auto = 0;
	var Opaque = 1;
	var PreMultiplied = 2;
	var PostMultiplied = 3;
	var Inherit = 4;
}
