// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract Backend(Int) from Int to Int {
	var Noop = 0;
	var Vulkan = 1;
	var Metal = 2;
	var Dx12 = 3;
	var Gl = 4;
	var BrowserWebGpu = 5;
}
