// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class Backends {
	public static inline var VULKAN:Int = 2;
	public static inline var METAL:Int = 4;
	public static inline var DX12:Int = 8;
	public static inline var GL:Int = 16;
	public static inline var BROWSER_WEBGPU:Int = 32;
}
