// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract BlendFactor(Int) from Int to Int {
	var Zero = 0;
	var One = 1;
	var Src = 2;
	var OneMinusSrc = 3;
	var SrcAlpha = 4;
	var OneMinusSrcAlpha = 5;
	var Dst = 6;
	var OneMinusDst = 7;
	var DstAlpha = 8;
	var OneMinusDstAlpha = 9;
	var SrcAlphaSaturated = 10;
	var Constant = 11;
	var OneMinusConstant = 12;
	var Src1 = 13;
	var OneMinusSrc1 = 14;
	var Src1Alpha = 15;
	var OneMinusSrc1Alpha = 16;
}
