// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract BlendOperation(Int) from Int to Int {
	var Add = 0;
	var Subtract = 1;
	var ReverseSubtract = 2;
	var Min = 3;
	var Max = 4;
}
