// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract BorderColor(Int) from Int to Int {
	var TransparentBlack = 0;
	var OpaqueBlack = 1;
	var OpaqueWhite = 2;
	var Zero = 3;
}
