// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class BufferUsage {
	public static inline var MAP_READ:Int = 0x0001;
	public static inline var MAP_WRITE:Int = 0x0002;
	public static inline var COPY_SRC:Int = 0x0004;
	public static inline var COPY_DST:Int = 0x0008;
	public static inline var INDEX:Int = 0x0010;
	public static inline var VERTEX:Int = 0x0020;
	public static inline var UNIFORM:Int = 0x0040;
	public static inline var STORAGE:Int = 0x0080;
	public static inline var INDIRECT:Int = 0x0100;
	public static inline var QUERY_RESOLVE:Int = 0x0200;
	public static inline var BLAS_INPUT:Int = 1024;
	public static inline var TLAS_INPUT:Int = 2048;
}
