// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract ColorSpace(Int) from Int to Int {
	var Auto = 0;
	var Srgb = 1;
	var ExtendedSrgbLinear = 2;
	var DisplayP3 = 3;
}
