// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class ColorWrite {
	public static inline var RED:Int = 0x1;
	public static inline var GREEN:Int = 0x2;
	public static inline var BLUE:Int = 0x4;
	public static inline var ALPHA:Int = 0x8;
	public static inline var ALL:Int = 0xF;
}
