// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract CompareFunction(Int) from Int to Int {
	var Never = 0;
	var Less = 1;
	var Equal = 2;
	var LessEqual = 3;
	var Greater = 4;
	var NotEqual = 5;
	var GreaterEqual = 6;
	var Always = 7;
}
