// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract DeviceType(Int) from Int to Int {
	var Other = 0;
	var IntegratedGpu = 1;
	var DiscreteGpu = 2;
	var VirtualGpu = 3;
	var Cpu = 4;
}
