// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract Feature(Int) from Int to Int {
	var CoreFeaturesAndLimits = 0;
	var DepthClipControl = 1;
	var Depth32floatStencil8 = 2;
	var TextureCompressionBc = 3;
	var TextureCompressionBcSliced3d = 4;
	var TextureCompressionEtc2 = 5;
	var TextureCompressionAstc = 6;
	var TextureCompressionAstcSliced3d = 7;
	var TimestampQuery = 8;
	var IndirectFirstInstance = 9;
	var ShaderF16 = 10;
	var Rg11b10ufloatRenderable = 11;
	var Bgra8unormStorage = 12;
	var Float32Filterable = 13;
	var Float32Blendable = 14;
	var ClipDistances = 15;
	var DualSourceBlending = 16;
	var Subgroups = 17;
	var TextureFormatsTier1 = 18;
	var TextureFormatsTier2 = 19;
	var PrimitiveIndex = 20;
	var TextureComponentSwizzle = 21;
	var SubgroupSizeControl = 22;
	var TextureCompressionUnaligned = 23;
}
