// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuAccelerationStructureBindingLayout")
extern class GpuAccelerationStructureBindingLayout {
	@:native("xidl_gpu_acceleration_structure_binding_layout_new")
	public function new();
	@:native("xidl_gpu_acceleration_structure_binding_layout_vertex_return")
	public function vertexReturn(value:Bool):Void;
}
