// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuAccelerationStructureBuild")
extern class GpuAccelerationStructureBuild {
	@:native("xgpu_gpu_acceleration_structure_build_new")
	public function new();
	@:native("xgpu_gpu_acceleration_structure_build_add_blases")
	public function addBlases(value:GpuBlasBuildEntry):Void;
	@:native("xgpu_gpu_acceleration_structure_build_add_tlases")
	public function addTlases(value:GpuTlas):Void;
}
