// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuAdapter")
extern class GpuAdapter {
	@:native("xgpu_gpu_adapter_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_adapter_name")
	public function name():String;
	@:native("xgpu_gpu_adapter_backend")
	public function backend():Backend;
	@:native("xgpu_gpu_adapter_limit")
	public function limit(which:Limit):haxe.Int64;
	@:native("xgpu_gpu_adapter_supports")
	public function supports(feature:Feature):Bool;
	@:native("xgpu_gpu_adapter_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_adapter_request_device")
	public function requestDevice():rayzor.concurrent.Future<GpuDevice>;
	@:native("xgpu_gpu_adapter_request_device_with")
	public function requestDeviceWith(descriptor:GpuDeviceDescriptor):rayzor.concurrent.Future<GpuDevice>;
	@:native("xgpu_gpu_adapter_driver")
	public function driver():String;
	@:native("xgpu_gpu_adapter_driver_info")
	public function driverInfo():String;
	@:native("xgpu_gpu_adapter_supports_native")
	public function supportsNative(feature:NativeFeature):Bool;
	@:native("xgpu_gpu_adapter_native_limit")
	public function nativeLimit(which:NativeLimit):haxe.Int64;
	@:native("xgpu_gpu_adapter_texture_format_usages")
	public function textureFormatUsages(format:TextureFormat):Int;
	@:native("xgpu_gpu_adapter_texture_format_features")
	public function textureFormatFeatures(format:TextureFormat):Int;
	@:native("xgpu_gpu_adapter_vendor_id")
	public function vendorId():haxe.Int64;
	@:native("xgpu_gpu_adapter_device_id")
	public function deviceId():haxe.Int64;
	@:native("xgpu_gpu_adapter_device_type")
	public function deviceType():DeviceType;
	@:native("xgpu_gpu_adapter_pci_bus_id")
	public function pciBusId():String;
	@:native("xgpu_gpu_adapter_subgroup_min_size")
	public function subgroupMinSize():Int;
	@:native("xgpu_gpu_adapter_subgroup_max_size")
	public function subgroupMaxSize():Int;
	@:native("xgpu_gpu_adapter_pipeline_cache_key")
	public function pipelineCacheKey():String;
}
