// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBindings")
extern class GpuBindings {
	@:native("xgpu_gpu_bindings_new")
	public function new();
	@:native("xgpu_gpu_bindings_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_bindings_buffer")
	public function buffer(buffer:GpuBuffer):Void;
	@:native("xgpu_gpu_bindings_texture")
	public function texture(view:GpuTextureView):Void;
	@:native("xgpu_gpu_bindings_sampler")
	public function sampler(sampler:GpuSampler):Void;
	@:native("xgpu_gpu_bindings_destroy")
	public function destroy():Void;
}
