// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBufferArray")
extern class GpuBufferArray {
	@:native("xidl_gpu_buffer_array_new")
	public function new();
	@:native("xidl_gpu_buffer_array_add_buffers")
	public function addBuffers(value:GpuBufferBinding):Void;
}
