// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBuffer")
extern class GpuBuffer {
	@:native("xidl_gpu_buffer_valid")
	public function valid():Bool;
	@:native("xidl_gpu_buffer_copy_out")
	public function copyOut(offset:haxe.Int64, out:haxe.io.Bytes, len:Int):Bool;
	@:native("xidl_gpu_buffer_copy_in")
	public function copyIn(offset:haxe.Int64, data:haxe.io.Bytes, len:Int):Bool;
	@:native("xidl_gpu_buffer_size")
	public function size():haxe.Int64;
	@:native("xidl_gpu_buffer_usage")
	public function usage():Int;
	@:native("xidl_gpu_buffer_unmap")
	public function unmap():Void;
	@:native("xidl_gpu_buffer_destroy")
	public function destroy():Void;

    /** Get the number of elements in this buffer. */
    @:native("rayzor_gpu_compute_buffer_numel")
    public function numel():Int;

    /** Get the dtype tag of this buffer. */
    @:native("rayzor_gpu_compute_buffer_dtype")
    public function dtype():rayzor.ds.DType;

    /**
     * Element-wise GPU addition (`a + b`).
     * Returns a new lazy GpuBuffer; the underlying kernel runs when the
     * result is read back via `GPUCompute.toTensor` / `.sum` / etc.
     */
    @:native("rayzor_gpu_buffer_add")
    @:op(A + B)
    public function add(other:GpuBuffer):GpuBuffer;

    /** Element-wise GPU subtraction (`a - b`). */
    @:native("rayzor_gpu_buffer_sub")
    @:op(A - B)
    public function sub(other:GpuBuffer):GpuBuffer;

    /** Element-wise GPU multiplication (`a * b`). */
    @:native("rayzor_gpu_buffer_mul")
    @:op(A * B)
    public function mul(other:GpuBuffer):GpuBuffer;

    /** Element-wise GPU division (`a / b`). */
    @:native("rayzor_gpu_buffer_div")
    @:op(A / B)
    public function div(other:GpuBuffer):GpuBuffer;
}
