// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlas")
extern class GpuBlas {
	@:native("xgpu_gpu_blas_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_blas_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_blas_prepare_compaction")
	public function prepareCompaction():rayzor.concurrent.Future<Void>;
	@:native("xgpu_gpu_blas_ready_for_compaction")
	public function readyForCompaction():Bool;
}
