// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlasAabbGeometry")
extern class GpuBlasAabbGeometry {
	@:native("xidl_gpu_blas_aabb_geometry_new")
	public function new(size:GpuBlasAabbGeometrySize, aabbBuffer:GpuBuffer, stride:haxe.Int64);
	@:native("xidl_gpu_blas_aabb_geometry_primitive_offset")
	public function primitiveOffset(value:Int):Void;
}
