// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlasBuildEntry")
extern class GpuBlasBuildEntry {
	@:native("xgpu_gpu_blas_build_entry_new")
	public function new(blas:GpuBlas);
	@:native("xgpu_gpu_blas_build_entry_add_triangles")
	public function addTriangles(value:GpuBlasTriangleGeometry):Void;
	@:native("xgpu_gpu_blas_build_entry_add_aabbs")
	public function addAabbs(value:GpuBlasAabbGeometry):Void;
}
