// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlendState")
extern class GpuBlendState {
	@:native("xgpu_gpu_blend_state_new")
	public function new(color:GpuBlendComponent, alpha:GpuBlendComponent);
}
