// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBindGroupLayoutEntry")
extern class GpuBindGroupLayoutEntry {
	@:native("xidl_gpu_bind_group_layout_entry_new")
	public function new(binding:Int, visibility:Int);
	@:native("xidl_gpu_bind_group_layout_entry_buffer")
	public function buffer(value:GpuBufferBindingLayout):Void;
	@:native("xidl_gpu_bind_group_layout_entry_sampler")
	public function sampler(value:GpuSamplerBindingLayout):Void;
	@:native("xidl_gpu_bind_group_layout_entry_texture")
	public function texture(value:GpuTextureBindingLayout):Void;
	@:native("xidl_gpu_bind_group_layout_entry_storage_texture")
	public function storageTexture(value:GpuStorageTextureBindingLayout):Void;
	@:native("xidl_gpu_bind_group_layout_entry_external_texture")
	public function externalTexture(value:GpuExternalTextureBindingLayout):Void;
	@:native("xidl_gpu_bind_group_layout_entry_count")
	public function count(value:Int):Void;
	@:native("xidl_gpu_bind_group_layout_entry_acceleration_structure")
	public function accelerationStructure(value:GpuAccelerationStructureBindingLayout):Void;
}
