// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBindGroupLayoutDescriptor")
extern class GpuBindGroupLayoutDescriptor {
	@:native("xidl_gpu_bind_group_layout_descriptor_new")
	public function new();
	@:native("xidl_gpu_bind_group_layout_descriptor_label")
	public function label(value:String):Void;
	@:native("xidl_gpu_bind_group_layout_descriptor_add_entries")
	public function addEntries(value:GpuBindGroupLayoutEntry):Void;
}
