// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBufferBinding")
extern class GpuBufferBinding {
	@:native("xgpu_gpu_buffer_binding_new")
	public function new(buffer:GpuBuffer);
	@:native("xgpu_gpu_buffer_binding_offset")
	public function offset(value:haxe.Int64):Void;
	@:native("xgpu_gpu_buffer_binding_size")
	public function size(value:haxe.Int64):Void;
}
