// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlasDescriptor")
extern class GpuBlasDescriptor {
	@:native("xidl_gpu_blas_descriptor_new")
	public function new();
	@:native("xidl_gpu_blas_descriptor_label")
	public function label(value:String):Void;
	@:native("xidl_gpu_blas_descriptor_flags")
	public function flags(value:Int):Void;
	@:native("xidl_gpu_blas_descriptor_update_mode")
	public function updateMode(value:AccelerationStructureUpdateMode):Void;
	@:native("xidl_gpu_blas_descriptor_add_triangles")
	public function addTriangles(value:GpuBlasTriangleGeometrySize):Void;
	@:native("xidl_gpu_blas_descriptor_add_aabbs")
	public function addAabbs(value:GpuBlasAabbGeometrySize):Void;
}
