// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBufferDescriptor")
extern class GpuBufferDescriptor {
	@:native("xidl_gpu_buffer_descriptor_new")
	public function new(size:haxe.Int64, usage:Int);
	@:native("xidl_gpu_buffer_descriptor_label")
	public function label(value:String):Void;
	@:native("xidl_gpu_buffer_descriptor_mapped_at_creation")
	public function mappedAtCreation(value:Bool):Void;
}
