// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBufferBindingLayout")
extern class GpuBufferBindingLayout {
	@:native("xgpu_gpu_buffer_binding_layout_new")
	public function new();
	@:native("xgpu_gpu_buffer_binding_layout_type")
	public function type(value:BufferBindingType):Void;
	@:native("xgpu_gpu_buffer_binding_layout_has_dynamic_offset")
	public function hasDynamicOffset(value:Bool):Void;
	@:native("xgpu_gpu_buffer_binding_layout_min_binding_size")
	public function minBindingSize(value:haxe.Int64):Void;
}
