// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBindGroupEntry")
extern class GpuBindGroupEntry {
	@:native("xidl_gpu_bind_group_entry_new")
	public function new(binding:Int);
	@:native("xidl_gpu_bind_group_entry_resource_sampler")
	public function resourceSampler(value:GpuSampler):Void;
	@:native("xidl_gpu_bind_group_entry_resource_texture")
	public function resourceTexture(value:GpuTexture):Void;
	@:native("xidl_gpu_bind_group_entry_resource_texture_view")
	public function resourceTextureView(value:GpuTextureView):Void;
	@:native("xidl_gpu_bind_group_entry_resource_buffer")
	public function resourceBuffer(value:GpuBuffer):Void;
	@:native("xidl_gpu_bind_group_entry_resource_buffer_binding")
	public function resourceBufferBinding(value:GpuBufferBinding):Void;
	@:native("xidl_gpu_bind_group_entry_resource_external_texture")
	public function resourceExternalTexture(value:GpuExternalTexture):Void;
	@:native("xidl_gpu_bind_group_entry_resource_buffer_array")
	public function resourceBufferArray(value:GpuBufferArray):Void;
	@:native("xidl_gpu_bind_group_entry_resource_sampler_array")
	public function resourceSamplerArray(value:GpuSamplerArray):Void;
	@:native("xidl_gpu_bind_group_entry_resource_texture_view_array")
	public function resourceTextureViewArray(value:GpuTextureViewArray):Void;
	@:native("xidl_gpu_bind_group_entry_resource_acceleration_structure")
	public function resourceAccelerationStructure(value:GpuTlas):Void;
	@:native("xidl_gpu_bind_group_entry_resource_acceleration_structure_array")
	public function resourceAccelerationStructureArray(value:GpuTlasArray):Void;
}
