// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBindGroup")
extern class GpuBindGroup {
	@:native("xgpu_gpu_bind_group_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_bind_group_destroy")
	public function destroy():Void;
}
