// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlasTriangleGeometry")
extern class GpuBlasTriangleGeometry {
	@:native("xgpu_gpu_blas_triangle_geometry_new")
	public function new(size:GpuBlasTriangleGeometrySize, vertexBuffer:GpuBuffer, vertexStride:haxe.Int64);
	@:native("xgpu_gpu_blas_triangle_geometry_first_vertex")
	public function firstVertex(value:Int):Void;
	@:native("xgpu_gpu_blas_triangle_geometry_index_buffer")
	public function indexBuffer(value:GpuBuffer):Void;
	@:native("xgpu_gpu_blas_triangle_geometry_first_index")
	public function firstIndex(value:Int):Void;
	@:native("xgpu_gpu_blas_triangle_geometry_transform_buffer")
	public function transformBuffer(value:GpuBuffer):Void;
	@:native("xgpu_gpu_blas_triangle_geometry_transform_buffer_offset")
	public function transformBufferOffset(value:haxe.Int64):Void;
}
