// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlasAabbGeometrySize")
extern class GpuBlasAabbGeometrySize {
	@:native("xidl_gpu_blas_aabb_geometry_size_new")
	public function new(primitiveCount:Int);
	@:native("xidl_gpu_blas_aabb_geometry_size_flags")
	public function flags(value:Int):Void;
}
