// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlasTriangleGeometrySize")
extern class GpuBlasTriangleGeometrySize {
	@:native("xidl_gpu_blas_triangle_geometry_size_new")
	public function new(vertexFormat:VertexFormat, vertexCount:Int);
	@:native("xidl_gpu_blas_triangle_geometry_size_index_format")
	public function indexFormat(value:IndexFormat):Void;
	@:native("xidl_gpu_blas_triangle_geometry_size_index_count")
	public function indexCount(value:Int):Void;
	@:native("xidl_gpu_blas_triangle_geometry_size_flags")
	public function flags(value:Int):Void;
}
