// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBlendComponent")
extern class GpuBlendComponent {
	@:native("xidl_gpu_blend_component_new")
	public function new();
	@:native("xidl_gpu_blend_component_operation")
	public function operation(value:BlendOperation):Void;
	@:native("xidl_gpu_blend_component_src_factor")
	public function srcFactor(value:BlendFactor):Void;
	@:native("xidl_gpu_blend_component_dst_factor")
	public function dstFactor(value:BlendFactor):Void;
}
