// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBindGroupLayout")
extern class GpuBindGroupLayout {
	@:native("xgpu_gpu_bind_group_layout_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_bind_group_layout_destroy")
	public function destroy():Void;
}
