// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuBindGroupDescriptor")
extern class GpuBindGroupDescriptor {
	@:native("xgpu_gpu_bind_group_descriptor_new")
	public function new(layout:GpuBindGroupLayout);
	@:native("xgpu_gpu_bind_group_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_bind_group_descriptor_add_entries")
	public function addEntries(value:GpuBindGroupEntry):Void;
}
