// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuComputePassTimestampWrites")
extern class GpuComputePassTimestampWrites {
	@:native("xgpu_gpu_compute_pass_timestamp_writes_new")
	public function new(querySet:GpuQuerySet);
	@:native("xgpu_gpu_compute_pass_timestamp_writes_beginning_of_pass_write_index")
	public function beginningOfPassWriteIndex(value:Int):Void;
	@:native("xgpu_gpu_compute_pass_timestamp_writes_end_of_pass_write_index")
	public function endOfPassWriteIndex(value:Int):Void;
}
