// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuComputePipelineDescriptor")
extern class GpuComputePipelineDescriptor {
	@:native("xgpu_gpu_compute_pipeline_descriptor_new")
	public function new(compute:GpuProgrammableStage);
	@:native("xgpu_gpu_compute_pipeline_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_compute_pipeline_descriptor_layout")
	public function layout(value:GpuPipelineLayout):Void;
	@:native("xgpu_gpu_compute_pipeline_descriptor_cache")
	public function cache(value:GpuPipelineCache):Void;
}
