// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuColorTargetState")
extern class GpuColorTargetState {
	@:native("xgpu_gpu_color_target_state_new")
	public function new(format:TextureFormat);
	@:native("xgpu_gpu_color_target_state_blend")
	public function blend(value:GpuBlendState):Void;
	@:native("xgpu_gpu_color_target_state_write_mask")
	public function writeMask(value:Int):Void;
}
