// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuCompilationInfo")
extern class GpuCompilationInfo {
	@:native("xidl_gpu_compilation_info_valid")
	public function valid():Bool;
	@:native("xidl_gpu_compilation_info_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_compilation_info_message_count")
	public function messageCount():Int;
	@:native("xidl_gpu_compilation_info_message")
	public function message(index:Int):String;
	@:native("xidl_gpu_compilation_info_message_type")
	public function messageType(index:Int):CompilationMessageType;
	@:native("xidl_gpu_compilation_info_line_num")
	public function lineNum(index:Int):haxe.Int64;
	@:native("xidl_gpu_compilation_info_line_pos")
	public function linePos(index:Int):haxe.Int64;
	@:native("xidl_gpu_compilation_info_offset")
	public function offset(index:Int):haxe.Int64;
	@:native("xidl_gpu_compilation_info_length")
	public function length(index:Int):haxe.Int64;
}
