// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuComputePassDescriptor")
extern class GpuComputePassDescriptor {
	@:native("xgpu_gpu_compute_pass_descriptor_new")
	public function new();
	@:native("xgpu_gpu_compute_pass_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_compute_pass_descriptor_timestamp_writes")
	public function timestampWrites(value:GpuComputePassTimestampWrites):Void;
}
