// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuColor")
extern class GpuColor {
	@:native("xgpu_gpu_color_new")
	public function new(r:Float, g:Float, b:Float, a:Float);
}
