// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuDeviceLostInfo")
extern class GpuDeviceLostInfo {
	@:native("xidl_gpu_device_lost_info_valid")
	public function valid():Bool;
	@:native("xidl_gpu_device_lost_info_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_device_lost_info_reason")
	public function reason():DeviceLostReason;
	@:native("xidl_gpu_device_lost_info_message")
	public function message():String;
}
