// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuDeviceDescriptor")
extern class GpuDeviceDescriptor {
	@:native("xgpu_gpu_device_descriptor_new")
	public function new();
	@:native("xgpu_gpu_device_descriptor_add_required_features")
	public function addRequiredFeatures(value:Feature):Void;
	@:native("xgpu_gpu_device_descriptor_add_required_limits")
	public function addRequiredLimits(key:Limit, value:haxe.Int64):Void;
	@:native("xgpu_gpu_device_descriptor_add_required_native_features")
	public function addRequiredNativeFeatures(value:NativeFeature):Void;
	@:native("xgpu_gpu_device_descriptor_add_required_native_limits")
	public function addRequiredNativeLimits(key:NativeLimit, value:haxe.Int64):Void;
	@:native("xgpu_gpu_device_descriptor_memory_hints")
	public function memoryHints(value:MemoryHints):Void;
	@:native("xgpu_gpu_device_descriptor_experimental_features")
	public function experimentalFeatures(value:Bool):Void;
	@:native("xgpu_gpu_device_descriptor_dont_care_loads")
	public function dontCareLoads(value:Bool):Void;
	@:native("xgpu_gpu_device_descriptor_trusted_shaders")
	public function trustedShaders(value:Bool):Void;
	@:native("xgpu_gpu_device_descriptor_pipeline_cache_data")
	public function pipelineCacheData(value:Bool):Void;
}
