// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuDepthStencilState")
extern class GpuDepthStencilState {
	@:native("xgpu_gpu_depth_stencil_state_new")
	public function new(format:TextureFormat);
	@:native("xgpu_gpu_depth_stencil_state_depth_write_enabled")
	public function depthWriteEnabled(value:Bool):Void;
	@:native("xgpu_gpu_depth_stencil_state_depth_compare")
	public function depthCompare(value:CompareFunction):Void;
	@:native("xgpu_gpu_depth_stencil_state_stencil_front")
	public function stencilFront(value:GpuStencilFaceState):Void;
	@:native("xgpu_gpu_depth_stencil_state_stencil_back")
	public function stencilBack(value:GpuStencilFaceState):Void;
	@:native("xgpu_gpu_depth_stencil_state_stencil_read_mask")
	public function stencilReadMask(value:Int):Void;
	@:native("xgpu_gpu_depth_stencil_state_stencil_write_mask")
	public function stencilWriteMask(value:Int):Void;
	@:native("xgpu_gpu_depth_stencil_state_depth_bias")
	public function depthBias(value:Int):Void;
	@:native("xgpu_gpu_depth_stencil_state_depth_bias_slope_scale")
	public function depthBiasSlopeScale(value:Float):Void;
	@:native("xgpu_gpu_depth_stencil_state_depth_bias_clamp")
	public function depthBiasClamp(value:Float):Void;
}
