// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuDevice")
extern class GpuDevice {
	@:native("xidl_gpu_device_valid")
	public function valid():Bool;
	@:native("xidl_gpu_device_take_error")
	public function takeError():String;
	@:native("xidl_gpu_device_queue")
	public function queue():GpuQueue;
	@:native("xidl_gpu_device_poll")
	public function poll():Void;
	@:native("xidl_gpu_device_limit")
	public function limit(which:Limit):haxe.Int64;
	@:native("xidl_gpu_device_supports")
	public function supports(feature:Feature):Bool;
	@:native("xidl_gpu_device_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_device_create_buffer")
	public function createBuffer(descriptor:GpuBufferDescriptor):GpuBuffer;
	@:native("xidl_gpu_device_map_buffer")
	public function mapBuffer(buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):rayzor.concurrent.Future<Void>;
	@:native("xidl_gpu_device_map_buffer_with")
	public function mapBufferWith(buffer:GpuBuffer, mode:Int, offset:haxe.Int64, size:haxe.Int64):rayzor.concurrent.Future<Void>;
	@:native("xidl_gpu_device_create_shader")
	public function createShader(wgsl:String):GpuShader;
	@:native("xidl_gpu_device_create_shader_module")
	public function createShaderModule(descriptor:GpuShaderModuleDescriptor):GpuShader;
	@:native("xidl_gpu_device_create_shader_passthrough")
	public function createShaderPassthrough(descriptor:GpuPassthroughShaderDescriptor):GpuShader;
	@:native("xidl_gpu_device_compute_pipeline")
	public function computePipeline(shader:GpuShader, entry:String):GpuPipeline;
	@:native("xidl_gpu_device_bind_group")
	public function bindGroup(pipeline:GpuPipeline, group:Int, bindings:GpuBindings):GpuBindGroup;
	@:native("xidl_gpu_device_encoder")
	public function encoder():GpuEncoder;
	@:native("xidl_gpu_device_queue_work_done")
	public function queueWorkDone(queue:GpuQueue):rayzor.concurrent.Future<Void>;
	@:native("xidl_gpu_device_texture")
	public function texture(descriptor:GpuTextureDescriptor):GpuTexture;
	@:native("xidl_gpu_device_pipeline")
	public function pipeline():GpuPipelineBuilder;
	@:native("xidl_gpu_device_sampler")
	public function sampler(descriptor:GpuSamplerDescriptor):GpuSampler;
	@:native("xidl_gpu_device_create_bind_group_layout")
	public function createBindGroupLayout(descriptor:GpuBindGroupLayoutDescriptor):GpuBindGroupLayout;
	@:native("xidl_gpu_device_create_pipeline_layout")
	public function createPipelineLayout(descriptor:GpuPipelineLayoutDescriptor):GpuPipelineLayout;
	@:native("xidl_gpu_device_create_bind_group")
	public function createBindGroup(descriptor:GpuBindGroupDescriptor):GpuBindGroup;
	@:native("xidl_gpu_device_create_compute_pipeline")
	public function createComputePipeline(descriptor:GpuComputePipelineDescriptor):GpuPipeline;
	@:native("xidl_gpu_device_create_compute_pipeline_async")
	public function createComputePipelineAsync(descriptor:GpuComputePipelineDescriptor):rayzor.concurrent.Future<GpuPipeline>;
	@:native("xidl_gpu_device_create_render_pipeline")
	public function createRenderPipeline(descriptor:GpuRenderPipelineDescriptor):GpuPipeline;
	@:native("xidl_gpu_device_create_render_pipeline_async")
	public function createRenderPipelineAsync(descriptor:GpuRenderPipelineDescriptor):rayzor.concurrent.Future<GpuPipeline>;
	@:native("xidl_gpu_device_create_query_set")
	public function createQuerySet(descriptor:GpuQuerySetDescriptor):GpuQuerySet;
	@:native("xidl_gpu_device_create_render_bundle_encoder")
	public function createRenderBundleEncoder(descriptor:GpuRenderBundleEncoderDescriptor):GpuRenderBundleEncoder;
	@:native("xidl_gpu_device_supports_native")
	public function supportsNative(feature:NativeFeature):Bool;
	@:native("xidl_gpu_device_native_limit")
	public function nativeLimit(which:NativeLimit):haxe.Int64;
	@:native("xidl_gpu_device_push_error_scope")
	public function pushErrorScope(filter:ErrorFilter):Void;
	@:native("xidl_gpu_device_pop_error_scope")
	public function popErrorScope():rayzor.concurrent.Future<GpuError>;
	@:native("xidl_gpu_device_lost")
	public function lost():rayzor.concurrent.Future<GpuDeviceLostInfo>;
	@:native("xidl_gpu_device_create_mesh_pipeline")
	public function createMeshPipeline(descriptor:GpuMeshPipelineDescriptor):GpuPipeline;
	@:native("xidl_gpu_device_create_mesh_pipeline_async")
	public function createMeshPipelineAsync(descriptor:GpuMeshPipelineDescriptor):rayzor.concurrent.Future<GpuPipeline>;
	@:native("xidl_gpu_device_create_external_texture")
	public function createExternalTexture(descriptor:GpuExternalTextureDescriptor):GpuExternalTexture;
	@:native("xidl_gpu_device_create_blas")
	public function createBlas(descriptor:GpuBlasDescriptor):GpuBlas;
	@:native("xidl_gpu_device_create_tlas")
	public function createTlas(descriptor:GpuTlasDescriptor):GpuTlas;
	@:native("xidl_gpu_device_create_pipeline_cache")
	public function createPipelineCache(descriptor:GpuPipelineCacheDescriptor):GpuPipelineCache;
	@:native("xidl_gpu_device_configure_surface_with")
	public function configureSurfaceWith(surface:GpuSurface, configuration:GpuSurfaceConfiguration):Void;
	@:native("xidl_gpu_device_configure_surface")
	public function configureSurface(surface:GpuSurface, width:Int, height:Int, format:TextureFormat):Void;
}
