// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuExternalTextureTransferFunction")
extern class GpuExternalTextureTransferFunction {
	@:native("xgpu_gpu_external_texture_transfer_function_new")
	public function new(a:Float, b:Float, g:Float, k:Float);
}
