// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuError")
extern class GpuError {
	@:native("xidl_gpu_error_valid")
	public function valid():Bool;
	@:native("xidl_gpu_error_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_error_filter")
	public function filter():ErrorFilter;
	@:native("xidl_gpu_error_message")
	public function message():String;
}
