// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuEncoder")
extern class GpuEncoder {
	@:native("xgpu_gpu_encoder_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_encoder_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_encoder_compute")
	public function compute(pipeline:GpuPipeline, bindgroup:GpuBindGroup, x:Int, y:Int, z:Int):Void;
	@:native("xgpu_gpu_encoder_copy_buffer")
	public function copyBuffer(src:GpuBuffer, src_offset:haxe.Int64, dst:GpuBuffer, dst_offset:haxe.Int64, size:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_submit")
	public function submit(queue:GpuQueue):Void;
	@:native("xgpu_gpu_encoder_pass_reset")
	public function passReset():Void;
	@:native("xgpu_gpu_encoder_pass_colour")
	public function passColour(view:GpuTextureView, r:Float, g:Float, b:Float, a:Float):Void;
	@:native("xgpu_gpu_encoder_pass_depth")
	public function passDepth(view:GpuTextureView, clear:Float, stencil_clear:Int):Void;
	@:native("xgpu_gpu_encoder_pass_begin")
	public function passBegin():Void;
	@:native("xgpu_gpu_encoder_render_set_pipeline")
	public function renderSetPipeline(pipeline:GpuPipeline):Void;
	@:native("xgpu_gpu_encoder_render_set_vertex_buffer")
	public function renderSetVertexBuffer(slot:Int, buffer:GpuBuffer):Void;
	@:native("xgpu_gpu_encoder_render_set_viewport")
	public function renderSetViewport(x:Float, y:Float, width:Float, height:Float, min_depth:Float, max_depth:Float):Void;
	@:native("xgpu_gpu_encoder_render_set_scissor_rect")
	public function renderSetScissorRect(x:Int, y:Int, width:Int, height:Int):Void;
	@:native("xgpu_gpu_encoder_render_draw")
	public function renderDraw(vertices:Int, instances:Int):Void;
	@:native("xgpu_gpu_encoder_render_end")
	public function renderEnd():Void;
	@:native("xgpu_gpu_encoder_copy_buffer_to_texture")
	public function copyBufferToTexture(buffer:GpuBuffer, bytes_per_row:Int, texture:GpuTexture, width:Int, height:Int):Void;
	@:native("xgpu_gpu_encoder_copy_texture_to_texture")
	public function copyTextureToTexture(src:GpuTexture, dst:GpuTexture, width:Int, height:Int):Void;
	@:native("xgpu_gpu_encoder_clear_buffer")
	public function clearBuffer(buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_copy_texture_to_buffer")
	public function copyTextureToBuffer(texture:GpuTexture, buffer:GpuBuffer, width:Int, height:Int, bytes_per_row:Int):Void;
	@:native("xgpu_gpu_encoder_render_set_bind_group")
	public function renderSetBindGroup(group:Int, bindgroup:GpuBindGroup):Void;
	@:native("xgpu_gpu_encoder_render_set_bind_group_offsets")
	public function renderSetBindGroupOffsets(group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void;
	@:native("xgpu_gpu_encoder_compute_begin")
	public function computeBegin():Void;
	@:native("xgpu_gpu_encoder_compute_set_pipeline")
	public function computeSetPipeline(pipeline:GpuPipeline):Void;
	@:native("xgpu_gpu_encoder_compute_set_bind_group")
	public function computeSetBindGroup(group:Int, bindgroup:GpuBindGroup):Void;
	@:native("xgpu_gpu_encoder_compute_set_bind_group_offsets")
	public function computeSetBindGroupOffsets(group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void;
	@:native("xgpu_gpu_encoder_compute_dispatch")
	public function computeDispatch(x:Int, y:Int, z:Int):Void;
	@:native("xgpu_gpu_encoder_compute_dispatch_indirect")
	public function computeDispatchIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_compute_end")
	public function computeEnd():Void;
	@:native("xgpu_gpu_encoder_begin_render_pass")
	public function beginRenderPass(descriptor:GpuRenderPassDescriptor):Void;
	@:native("xgpu_gpu_encoder_begin_compute_pass")
	public function beginComputePass(descriptor:GpuComputePassDescriptor):Void;
	@:native("xgpu_gpu_encoder_render_draw_range")
	public function renderDrawRange(vertex_count:Int, instance_count:Int, first_vertex:Int, first_instance:Int):Void;
	@:native("xgpu_gpu_encoder_render_draw_indexed_range")
	public function renderDrawIndexedRange(index_count:Int, instance_count:Int, first_index:Int, base_vertex:Int, first_instance:Int):Void;
	@:native("xgpu_gpu_encoder_render_set_vertex_buffer_range")
	public function renderSetVertexBufferRange(slot:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_render_set_index_buffer_range")
	public function renderSetIndexBufferRange(buffer:GpuBuffer, format:IndexFormat, offset:haxe.Int64, size:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_render_multi_draw_indirect")
	public function renderMultiDrawIndirect(buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void;
	@:native("xgpu_gpu_encoder_render_multi_draw_indexed_indirect")
	public function renderMultiDrawIndexedIndirect(buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void;
	@:native("xgpu_gpu_encoder_render_multi_draw_indirect_count")
	public function renderMultiDrawIndirectCount(buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void;
	@:native("xgpu_gpu_encoder_render_multi_draw_indexed_indirect_count")
	public function renderMultiDrawIndexedIndirectCount(buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void;
	@:native("xgpu_gpu_encoder_render_set_immediates")
	public function renderSetImmediates(offset:Int, data:haxe.io.Bytes, start:haxe.Int64, size:Int):Void;
	@:native("xgpu_gpu_encoder_compute_set_immediates")
	public function computeSetImmediates(offset:Int, data:haxe.io.Bytes, start:haxe.Int64, size:Int):Void;
	@:native("xgpu_gpu_encoder_render_begin_occlusion_query")
	public function renderBeginOcclusionQuery(index:Int):Void;
	@:native("xgpu_gpu_encoder_render_end_occlusion_query")
	public function renderEndOcclusionQuery():Void;
	@:native("xgpu_gpu_encoder_render_begin_pipeline_statistics_query")
	public function renderBeginPipelineStatisticsQuery(query_set:GpuQuerySet, index:Int):Void;
	@:native("xgpu_gpu_encoder_render_end_pipeline_statistics_query")
	public function renderEndPipelineStatisticsQuery():Void;
	@:native("xgpu_gpu_encoder_compute_begin_pipeline_statistics_query")
	public function computeBeginPipelineStatisticsQuery(query_set:GpuQuerySet, index:Int):Void;
	@:native("xgpu_gpu_encoder_compute_end_pipeline_statistics_query")
	public function computeEndPipelineStatisticsQuery():Void;
	@:native("xgpu_gpu_encoder_write_timestamp")
	public function writeTimestamp(query_set:GpuQuerySet, index:Int):Void;
	@:native("xgpu_gpu_encoder_render_write_timestamp")
	public function renderWriteTimestamp(query_set:GpuQuerySet, index:Int):Void;
	@:native("xgpu_gpu_encoder_compute_write_timestamp")
	public function computeWriteTimestamp(query_set:GpuQuerySet, index:Int):Void;
	@:native("xgpu_gpu_encoder_resolve_query_set")
	public function resolveQuerySet(query_set:GpuQuerySet, first:Int, count:Int, destination:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_render_execute_bundle")
	public function renderExecuteBundle(bundle:GpuRenderBundle):Void;
	@:native("xgpu_gpu_encoder_render_draw_mesh_tasks")
	public function renderDrawMeshTasks(x:Int, y:Int, z:Int):Void;
	@:native("xgpu_gpu_encoder_render_draw_mesh_tasks_indirect")
	public function renderDrawMeshTasksIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_render_multi_draw_mesh_tasks_indirect")
	public function renderMultiDrawMeshTasksIndirect(buffer:GpuBuffer, offset:haxe.Int64, count:Int):Void;
	@:native("xgpu_gpu_encoder_render_multi_draw_mesh_tasks_indirect_count")
	public function renderMultiDrawMeshTasksIndirectCount(buffer:GpuBuffer, offset:haxe.Int64, count_buffer:GpuBuffer, count_offset:haxe.Int64, max_count:Int):Void;
	@:native("xgpu_gpu_encoder_build_acceleration_structures")
	public function buildAccelerationStructures(build:GpuAccelerationStructureBuild):Void;
	@:native("xgpu_gpu_encoder_copy_buffer_to_texture_with")
	public function copyBufferToTextureWith(source:GpuTexelCopyBufferInfo, destination:GpuTexelCopyTextureInfo, size:GpuExtent3D):Void;
	@:native("xgpu_gpu_encoder_copy_texture_to_buffer_with")
	public function copyTextureToBufferWith(source:GpuTexelCopyTextureInfo, destination:GpuTexelCopyBufferInfo, size:GpuExtent3D):Void;
	@:native("xgpu_gpu_encoder_copy_texture_to_texture_with")
	public function copyTextureToTextureWith(source:GpuTexelCopyTextureInfo, destination:GpuTexelCopyTextureInfo, size:GpuExtent3D):Void;
	@:native("xgpu_gpu_encoder_clear_texture")
	public function clearTexture(texture:GpuTexture):Void;
	@:native("xgpu_gpu_encoder_render_set_index_buffer")
	public function renderSetIndexBuffer(buffer:GpuBuffer, format:IndexFormat):Void;
	@:native("xgpu_gpu_encoder_render_draw_indexed")
	public function renderDrawIndexed(indices:Int, instances:Int):Void;
	@:native("xgpu_gpu_encoder_render_set_blend_constant")
	public function renderSetBlendConstant(r:Float, g:Float, b:Float, a:Float):Void;
	@:native("xgpu_gpu_encoder_render_set_stencil_reference")
	public function renderSetStencilReference(reference:Int):Void;
	@:native("xgpu_gpu_encoder_compute_indirect")
	public function computeIndirect(pipeline:GpuPipeline, bindgroup:GpuBindGroup, buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_render_draw_indirect")
	public function renderDrawIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_render_draw_indexed_indirect")
	public function renderDrawIndexedIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_encoder_push_debug_group")
	public function pushDebugGroup(label:String):Void;
	@:native("xgpu_gpu_encoder_pop_debug_group")
	public function popDebugGroup():Void;
	@:native("xgpu_gpu_encoder_insert_debug_marker")
	public function insertDebugMarker(label:String):Void;
}
