// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuExternalTextureBindingLayout")
extern class GpuExternalTextureBindingLayout {
	@:native("xgpu_gpu_external_texture_binding_layout_new")
	public function new();
}
