// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuExternalTexture")
extern class GpuExternalTexture {
	@:native("xidl_gpu_external_texture_valid")
	public function valid():Bool;
	@:native("xidl_gpu_external_texture_destroy")
	public function destroy():Void;
}
