// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuExternalTextureDescriptor")
extern class GpuExternalTextureDescriptor {
	@:native("xgpu_gpu_external_texture_descriptor_new")
	public function new(format:ExternalTextureFormat);
	@:native("xgpu_gpu_external_texture_descriptor_add_planes")
	public function addPlanes(value:GpuTextureView):Void;
	@:native("xgpu_gpu_external_texture_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_external_texture_descriptor_width")
	public function width(value:Int):Void;
	@:native("xgpu_gpu_external_texture_descriptor_height")
	public function height(value:Int):Void;
	@:native("xgpu_gpu_external_texture_descriptor_add_yuv_conversion_matrix")
	public function addYuvConversionMatrix(value:Float):Void;
	@:native("xgpu_gpu_external_texture_descriptor_add_gamut_conversion_matrix")
	public function addGamutConversionMatrix(value:Float):Void;
	@:native("xgpu_gpu_external_texture_descriptor_add_sample_transform")
	public function addSampleTransform(value:Float):Void;
	@:native("xgpu_gpu_external_texture_descriptor_add_load_transform")
	public function addLoadTransform(value:Float):Void;
	@:native("xgpu_gpu_external_texture_descriptor_src_transfer_function")
	public function srcTransferFunction(value:GpuExternalTextureTransferFunction):Void;
	@:native("xgpu_gpu_external_texture_descriptor_dst_transfer_function")
	public function dstTransferFunction(value:GpuExternalTextureTransferFunction):Void;
}
