// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuExtent3D")
extern class GpuExtent3D {
	@:native("xidl_gpu_extent3_d_new")
	public function new(width:Int);
	@:native("xidl_gpu_extent3_d_height")
	public function height(value:Int):Void;
	@:native("xidl_gpu_extent3_d_depth_or_array_layers")
	public function depthOrArrayLayers(value:Int):Void;
}
