// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuFragmentState")
extern class GpuFragmentState {
	@:native("xgpu_gpu_fragment_state_new")
	public function new(module:GpuShader);
	@:native("xgpu_gpu_fragment_state_entry_point")
	public function entryPoint(value:String):Void;
	@:native("xgpu_gpu_fragment_state_add_constants")
	public function addConstants(key:String, value:Float):Void;
	@:native("xgpu_gpu_fragment_state_add_targets")
	public function addTargets(value:GpuColorTargetState):Void;
}
