// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuInstance")
extern class GpuInstance {
	@:native("xidl_gpu_instance_valid")
	public function valid():Bool;
	@:native("xidl_gpu_instance_new")
	public function new();
	@:native("xidl_gpu_instance_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_instance_request_adapter")
	public function requestAdapter(power:Power):rayzor.concurrent.Future<GpuAdapter>;
	@:native("xidl_gpu_instance_create_with")
	public static function createWith(descriptor:GpuInstanceDescriptor):GpuInstance;
	@:native("xidl_gpu_instance_request_adapter_with")
	public function requestAdapterWith(options:GpuRequestAdapterOptions):rayzor.concurrent.Future<GpuAdapter>;
	@:native("xidl_gpu_instance_surface")
	public function surface(platform:Int, wa:haxe.Int64, wb:haxe.Int64, da:haxe.Int64, db:haxe.Int64):GpuSurface;
}
