// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuInstanceDescriptor")
extern class GpuInstanceDescriptor {
	@:native("xgpu_gpu_instance_descriptor_new")
	public function new();
	@:native("xgpu_gpu_instance_descriptor_backends")
	public function backends(value:Int):Void;
	@:native("xgpu_gpu_instance_descriptor_flags")
	public function flags(value:Int):Void;
}
