// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuMultisampleState")
extern class GpuMultisampleState {
	@:native("xidl_gpu_multisample_state_new")
	public function new();
	@:native("xidl_gpu_multisample_state_count")
	public function count(value:Int):Void;
	@:native("xidl_gpu_multisample_state_mask")
	public function mask(value:Int):Void;
	@:native("xidl_gpu_multisample_state_alpha_to_coverage_enabled")
	public function alphaToCoverageEnabled(value:Bool):Void;
}
