// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuOrigin3D")
extern class GpuOrigin3D {
	@:native("xidl_gpu_origin3_d_new")
	public function new();
	@:native("xidl_gpu_origin3_d_x")
	public function x(value:Int):Void;
	@:native("xidl_gpu_origin3_d_y")
	public function y(value:Int):Void;
	@:native("xidl_gpu_origin3_d_z")
	public function z(value:Int):Void;
}
