// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPipelineCache")
extern class GpuPipelineCache {
	@:native("xgpu_gpu_pipeline_cache_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_pipeline_cache_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_pipeline_cache_get_data")
	public function getData():haxe.io.Bytes;
}
