// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPipelineLayout")
extern class GpuPipelineLayout {
	@:native("xidl_gpu_pipeline_layout_valid")
	public function valid():Bool;
	@:native("xidl_gpu_pipeline_layout_destroy")
	public function destroy():Void;
}
