// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuProgrammableStage")
extern class GpuProgrammableStage {
	@:native("xgpu_gpu_programmable_stage_new")
	public function new(module:GpuShader);
	@:native("xgpu_gpu_programmable_stage_entry_point")
	public function entryPoint(value:String):Void;
	@:native("xgpu_gpu_programmable_stage_add_constants")
	public function addConstants(key:String, value:Float):Void;
}
