// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPassthroughShaderDescriptor")
extern class GpuPassthroughShaderDescriptor {
	@:native("xgpu_gpu_passthrough_shader_descriptor_new")
	public function new();
	@:native("xgpu_gpu_passthrough_shader_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_passthrough_shader_descriptor_add_entry_points")
	public function addEntryPoints(value:GpuPassthroughEntryPoint):Void;
	@:native("xgpu_gpu_passthrough_shader_descriptor_spirv")
	public function spirv(value:haxe.io.Bytes):Void;
	@:native("xgpu_gpu_passthrough_shader_descriptor_dxil")
	public function dxil(value:haxe.io.Bytes):Void;
	@:native("xgpu_gpu_passthrough_shader_descriptor_hlsl")
	public function hlsl(value:String):Void;
	@:native("xgpu_gpu_passthrough_shader_descriptor_metallib")
	public function metallib(value:haxe.io.Bytes):Void;
	@:native("xgpu_gpu_passthrough_shader_descriptor_msl")
	public function msl(value:String):Void;
	@:native("xgpu_gpu_passthrough_shader_descriptor_wgsl")
	public function wgsl(value:String):Void;
}
