// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPrimitiveState")
extern class GpuPrimitiveState {
	@:native("xgpu_gpu_primitive_state_new")
	public function new();
	@:native("xgpu_gpu_primitive_state_topology")
	public function topology(value:PrimitiveTopology):Void;
	@:native("xgpu_gpu_primitive_state_strip_index_format")
	public function stripIndexFormat(value:IndexFormat):Void;
	@:native("xgpu_gpu_primitive_state_front_face")
	public function frontFace(value:FrontFace):Void;
	@:native("xgpu_gpu_primitive_state_cull_mode")
	public function cullMode(value:CullMode):Void;
	@:native("xgpu_gpu_primitive_state_unclipped_depth")
	public function unclippedDepth(value:Bool):Void;
	@:native("xgpu_gpu_primitive_state_polygon_mode")
	public function polygonMode(value:PolygonMode):Void;
	@:native("xgpu_gpu_primitive_state_conservative")
	public function conservative(value:Bool):Void;
}
