// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPipelineCacheDescriptor")
extern class GpuPipelineCacheDescriptor {
	@:native("xgpu_gpu_pipeline_cache_descriptor_new")
	public function new();
	@:native("xgpu_gpu_pipeline_cache_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_pipeline_cache_descriptor_data")
	public function data(value:haxe.io.Bytes):Void;
	@:native("xgpu_gpu_pipeline_cache_descriptor_fallback")
	public function fallback(value:Bool):Void;
}
