// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPassthroughEntryPoint")
extern class GpuPassthroughEntryPoint {
	@:native("xidl_gpu_passthrough_entry_point_new")
	public function new(name:String);
	@:native("xidl_gpu_passthrough_entry_point_workgroup_x")
	public function workgroupX(value:Int):Void;
	@:native("xidl_gpu_passthrough_entry_point_workgroup_y")
	public function workgroupY(value:Int):Void;
	@:native("xidl_gpu_passthrough_entry_point_workgroup_z")
	public function workgroupZ(value:Int):Void;
}
