// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPipelineBuilder")
extern class GpuPipelineBuilder {
	@:native("xgpu_gpu_pipeline_builder_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_pipeline_builder_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_pipeline_builder_shader")
	public function shader(shader:GpuShader, vs:String, fs:String):Void;
	@:native("xgpu_gpu_pipeline_builder_layout")
	public function layout(layout:GpuPipelineLayout):Void;
	@:native("xgpu_gpu_pipeline_builder_vertex_buffer")
	public function vertexBuffer(stride:haxe.Int64, step:VertexStepMode):Void;
	@:native("xgpu_gpu_pipeline_builder_attribute_packed")
	public function attributePacked(format:VertexFormat):Void;
	@:native("xgpu_gpu_pipeline_builder_attribute")
	public function attribute(format:VertexFormat, offset:haxe.Int64, location:Int):Void;
	@:native("xgpu_gpu_pipeline_builder_target")
	public function target(format:TextureFormat, write_mask:Int):Void;
	@:native("xgpu_gpu_pipeline_builder_blend")
	public function blend(src:BlendFactor, dst:BlendFactor, op:BlendOperation, src_alpha:BlendFactor, dst_alpha:BlendFactor, op_alpha:BlendOperation):Void;
	@:native("xgpu_gpu_pipeline_builder_stencil")
	public function stencil(compare:CompareFunction, fail:StencilOperation, depth_fail:StencilOperation, pass_op:StencilOperation, read_mask:Int, write_mask:Int):Void;
	@:native("xgpu_gpu_pipeline_builder_depth")
	public function depth(format:TextureFormat, write:Bool, compare:CompareFunction):Void;
	@:native("xgpu_gpu_pipeline_builder_primitive")
	public function primitive(topology:PrimitiveTopology, cull:CullMode, front:FrontFace):Void;
	@:native("xgpu_gpu_pipeline_builder_build")
	public function build():GpuPipeline;
}
