// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPipelineLayoutDescriptor")
extern class GpuPipelineLayoutDescriptor {
	@:native("xgpu_gpu_pipeline_layout_descriptor_new")
	public function new();
	@:native("xgpu_gpu_pipeline_layout_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_pipeline_layout_descriptor_add_bind_group_layouts")
	public function addBindGroupLayouts(value:GpuBindGroupLayout):Void;
	@:native("xgpu_gpu_pipeline_layout_descriptor_immediate_size")
	public function immediateSize(value:Int):Void;
}
