// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuPipeline")
extern class GpuPipeline {
	@:native("xidl_gpu_pipeline_valid")
	public function valid():Bool;
	@:native("xidl_gpu_pipeline_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_pipeline_get_bind_group_layout")
	public function getBindGroupLayout(index:Int):GpuBindGroupLayout;
}
