// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuQuerySet")
extern class GpuQuerySet {
	@:native("xgpu_gpu_query_set_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_query_set_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_query_set_count")
	public function count():Int;
	@:native("xgpu_gpu_query_set_query_type")
	public function queryType():QueryType;
}
