// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuQueue")
extern class GpuQueue {
	@:native("xgpu_gpu_queue_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_queue_write_buffer")
	public function writeBuffer(buffer:GpuBuffer, offset:haxe.Int64, data:haxe.io.Bytes, len:Int):Void;
	@:native("xgpu_gpu_queue_write_texture")
	public function writeTexture(texture:GpuTexture, data:haxe.io.Bytes, width:Int, height:Int, bytes_per_row:Int):Void;
	@:native("xgpu_gpu_queue_present_surface")
	public function presentSurface(surface:GpuSurface):Void;
	@:native("xgpu_gpu_queue_write_texture_with")
	public function writeTextureWith(destination:GpuTexelCopyTextureInfo, data:haxe.io.Bytes, layout:GpuTexelCopyBufferLayout, size:GpuExtent3D):Void;
	@:native("xgpu_gpu_queue_timestamp_period")
	public function timestampPeriod():Float;
	@:native("xgpu_gpu_queue_compact_blas")
	public function compactBlas(blas:GpuBlas):GpuBlas;
}
