// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuQuerySetDescriptor")
extern class GpuQuerySetDescriptor {
	@:native("xidl_gpu_query_set_descriptor_new")
	public function new(type:QueryType, count:Int);
	@:native("xidl_gpu_query_set_descriptor_label")
	public function label(value:String):Void;
	@:native("xidl_gpu_query_set_descriptor_pipeline_statistics")
	public function pipelineStatistics(value:Int):Void;
}
