// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRequestAdapterOptions")
extern class GpuRequestAdapterOptions {
	@:native("xidl_gpu_request_adapter_options_new")
	public function new();
	@:native("xidl_gpu_request_adapter_options_power_preference")
	public function powerPreference(value:Power):Void;
	@:native("xidl_gpu_request_adapter_options_force_fallback_adapter")
	public function forceFallbackAdapter(value:Bool):Void;
	@:native("xidl_gpu_request_adapter_options_compatible_surface")
	public function compatibleSurface(value:GpuSurface):Void;
}
