// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderPassColorAttachment")
extern class GpuRenderPassColorAttachment {
	@:native("xgpu_gpu_render_pass_color_attachment_new")
	public function new(loadOp:LoadOp, storeOp:StoreOp);
	@:native("xgpu_gpu_render_pass_color_attachment_view_texture")
	public function viewTexture(value:GpuTexture):Void;
	@:native("xgpu_gpu_render_pass_color_attachment_view_texture_view")
	public function viewTextureView(value:GpuTextureView):Void;
	@:native("xgpu_gpu_render_pass_color_attachment_depth_slice")
	public function depthSlice(value:Int):Void;
	@:native("xgpu_gpu_render_pass_color_attachment_resolve_target_texture")
	public function resolveTargetTexture(value:GpuTexture):Void;
	@:native("xgpu_gpu_render_pass_color_attachment_resolve_target_texture_view")
	public function resolveTargetTextureView(value:GpuTextureView):Void;
	@:native("xgpu_gpu_render_pass_color_attachment_clear_value")
	public function clearValue(value:GpuColor):Void;
}
