// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderBundle")
extern class GpuRenderBundle {
	@:native("xgpu_gpu_render_bundle_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_render_bundle_destroy")
	public function destroy():Void;
}
