// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderBundleEncoderDescriptor")
extern class GpuRenderBundleEncoderDescriptor {
	@:native("xidl_gpu_render_bundle_encoder_descriptor_new")
	public function new();
	@:native("xidl_gpu_render_bundle_encoder_descriptor_label")
	public function label(value:String):Void;
	@:native("xidl_gpu_render_bundle_encoder_descriptor_add_color_formats")
	public function addColorFormats(value:TextureFormat):Void;
	@:native("xidl_gpu_render_bundle_encoder_descriptor_depth_stencil_format")
	public function depthStencilFormat(value:TextureFormat):Void;
	@:native("xidl_gpu_render_bundle_encoder_descriptor_sample_count")
	public function sampleCount(value:Int):Void;
	@:native("xidl_gpu_render_bundle_encoder_descriptor_depth_read_only")
	public function depthReadOnly(value:Bool):Void;
	@:native("xidl_gpu_render_bundle_encoder_descriptor_stencil_read_only")
	public function stencilReadOnly(value:Bool):Void;
}
