// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderPassTimestampWrites")
extern class GpuRenderPassTimestampWrites {
	@:native("xidl_gpu_render_pass_timestamp_writes_new")
	public function new(querySet:GpuQuerySet);
	@:native("xidl_gpu_render_pass_timestamp_writes_beginning_of_pass_write_index")
	public function beginningOfPassWriteIndex(value:Int):Void;
	@:native("xidl_gpu_render_pass_timestamp_writes_end_of_pass_write_index")
	public function endOfPassWriteIndex(value:Int):Void;
}
