// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderPassDescriptor")
extern class GpuRenderPassDescriptor {
	@:native("xidl_gpu_render_pass_descriptor_new")
	public function new();
	@:native("xidl_gpu_render_pass_descriptor_label")
	public function label(value:String):Void;
	@:native("xidl_gpu_render_pass_descriptor_add_color_attachments")
	public function addColorAttachments(value:GpuRenderPassColorAttachment):Void;
	@:native("xidl_gpu_render_pass_descriptor_depth_stencil_attachment")
	public function depthStencilAttachment(value:GpuRenderPassDepthStencilAttachment):Void;
	@:native("xidl_gpu_render_pass_descriptor_occlusion_query_set")
	public function occlusionQuerySet(value:GpuQuerySet):Void;
	@:native("xidl_gpu_render_pass_descriptor_timestamp_writes")
	public function timestampWrites(value:GpuRenderPassTimestampWrites):Void;
	@:native("xidl_gpu_render_pass_descriptor_max_draw_count")
	public function maxDrawCount(value:haxe.Int64):Void;
}
