// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderBundleEncoder")
extern class GpuRenderBundleEncoder {
	@:native("xgpu_gpu_render_bundle_encoder_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_render_bundle_encoder_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_render_bundle_encoder_set_pipeline")
	public function setPipeline(pipeline:GpuPipeline):Void;
	@:native("xgpu_gpu_render_bundle_encoder_set_bind_group")
	public function setBindGroup(group:Int, bindgroup:GpuBindGroup):Void;
	@:native("xgpu_gpu_render_bundle_encoder_set_bind_group_offsets")
	public function setBindGroupOffsets(group:Int, bindgroup:GpuBindGroup, offsets:haxe.io.Bytes, start:haxe.Int64, count:Int):Void;
	@:native("xgpu_gpu_render_bundle_encoder_set_vertex_buffer")
	public function setVertexBuffer(slot:Int, buffer:GpuBuffer, offset:haxe.Int64, size:haxe.Int64):Void;
	@:native("xgpu_gpu_render_bundle_encoder_set_index_buffer")
	public function setIndexBuffer(buffer:GpuBuffer, format:IndexFormat, offset:haxe.Int64, size:haxe.Int64):Void;
	@:native("xgpu_gpu_render_bundle_encoder_draw")
	public function draw(vertex_count:Int, instance_count:Int, first_vertex:Int, first_instance:Int):Void;
	@:native("xgpu_gpu_render_bundle_encoder_draw_indexed")
	public function drawIndexed(index_count:Int, instance_count:Int, first_index:Int, base_vertex:Int, first_instance:Int):Void;
	@:native("xgpu_gpu_render_bundle_encoder_draw_indirect")
	public function drawIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_render_bundle_encoder_draw_indexed_indirect")
	public function drawIndexedIndirect(buffer:GpuBuffer, offset:haxe.Int64):Void;
	@:native("xgpu_gpu_render_bundle_encoder_finish")
	public function finish():GpuRenderBundle;
}
