// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderPassDepthStencilAttachment")
extern class GpuRenderPassDepthStencilAttachment {
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_new")
	public function new();
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_view_texture")
	public function viewTexture(value:GpuTexture):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_view_texture_view")
	public function viewTextureView(value:GpuTextureView):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_depth_clear_value")
	public function depthClearValue(value:Float):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_depth_load_op")
	public function depthLoadOp(value:LoadOp):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_depth_store_op")
	public function depthStoreOp(value:StoreOp):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_depth_read_only")
	public function depthReadOnly(value:Bool):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_stencil_clear_value")
	public function stencilClearValue(value:Int):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_stencil_load_op")
	public function stencilLoadOp(value:LoadOp):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_stencil_store_op")
	public function stencilStoreOp(value:StoreOp):Void;
	@:native("xgpu_gpu_render_pass_depth_stencil_attachment_stencil_read_only")
	public function stencilReadOnly(value:Bool):Void;
}
