// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuRenderPipelineDescriptor")
extern class GpuRenderPipelineDescriptor {
	@:native("xgpu_gpu_render_pipeline_descriptor_new")
	public function new(vertex:GpuVertexState);
	@:native("xgpu_gpu_render_pipeline_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_render_pipeline_descriptor_layout")
	public function layout(value:GpuPipelineLayout):Void;
	@:native("xgpu_gpu_render_pipeline_descriptor_primitive")
	public function primitive(value:GpuPrimitiveState):Void;
	@:native("xgpu_gpu_render_pipeline_descriptor_depth_stencil")
	public function depthStencil(value:GpuDepthStencilState):Void;
	@:native("xgpu_gpu_render_pipeline_descriptor_multisample")
	public function multisample(value:GpuMultisampleState):Void;
	@:native("xgpu_gpu_render_pipeline_descriptor_fragment")
	public function fragment(value:GpuFragmentState):Void;
	@:native("xgpu_gpu_render_pipeline_descriptor_multiview_mask")
	public function multiviewMask(value:Int):Void;
	@:native("xgpu_gpu_render_pipeline_descriptor_cache")
	public function cache(value:GpuPipelineCache):Void;
}
