// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuStorageTextureBindingLayout")
extern class GpuStorageTextureBindingLayout {
	@:native("xgpu_gpu_storage_texture_binding_layout_new")
	public function new(format:TextureFormat);
	@:native("xgpu_gpu_storage_texture_binding_layout_access")
	public function access(value:StorageTextureAccess):Void;
	@:native("xgpu_gpu_storage_texture_binding_layout_view_dimension")
	public function viewDimension(value:TextureViewDimension):Void;
}
