// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuSamplerArray")
extern class GpuSamplerArray {
	@:native("xidl_gpu_sampler_array_new")
	public function new();
	@:native("xidl_gpu_sampler_array_add_samplers")
	public function addSamplers(value:GpuSampler):Void;
}
