// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuSurfaceCapabilities")
extern class GpuSurfaceCapabilities {
	@:native("xidl_gpu_surface_capabilities_valid")
	public function valid():Bool;
	@:native("xidl_gpu_surface_capabilities_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_surface_capabilities_format_count")
	public function formatCount():Int;
	@:native("xidl_gpu_surface_capabilities_format")
	public function format(index:Int):TextureFormat;
	@:native("xidl_gpu_surface_capabilities_present_mode_count")
	public function presentModeCount():Int;
	@:native("xidl_gpu_surface_capabilities_present_mode")
	public function presentMode(index:Int):PresentMode;
	@:native("xidl_gpu_surface_capabilities_alpha_mode_count")
	public function alphaModeCount():Int;
	@:native("xidl_gpu_surface_capabilities_alpha_mode")
	public function alphaMode(index:Int):AlphaMode;
	@:native("xidl_gpu_surface_capabilities_usages")
	public function usages():Int;
}
