// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuShaderModuleDescriptor")
extern class GpuShaderModuleDescriptor {
	@:native("xgpu_gpu_shader_module_descriptor_new")
	public function new(code:String);
	@:native("xgpu_gpu_shader_module_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_shader_module_descriptor_bounds_checks")
	public function boundsChecks(value:Bool):Void;
	@:native("xgpu_gpu_shader_module_descriptor_force_loop_bounding")
	public function forceLoopBounding(value:Bool):Void;
	@:native("xgpu_gpu_shader_module_descriptor_ray_query_initialization_tracking")
	public function rayQueryInitializationTracking(value:Bool):Void;
	@:native("xgpu_gpu_shader_module_descriptor_task_shader_dispatch_tracking")
	public function taskShaderDispatchTracking(value:Bool):Void;
	@:native("xgpu_gpu_shader_module_descriptor_mesh_shader_primitive_indices_clamp")
	public function meshShaderPrimitiveIndicesClamp(value:Bool):Void;
	@:native("xgpu_gpu_shader_module_descriptor_int_div_checks")
	public function intDivChecks(value:Bool):Void;
}
