// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuSamplerDescriptor")
extern class GpuSamplerDescriptor {
	@:native("xgpu_gpu_sampler_descriptor_new")
	public function new();
	@:native("xgpu_gpu_sampler_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_sampler_descriptor_address_mode_u")
	public function addressModeU(value:AddressMode):Void;
	@:native("xgpu_gpu_sampler_descriptor_address_mode_v")
	public function addressModeV(value:AddressMode):Void;
	@:native("xgpu_gpu_sampler_descriptor_address_mode_w")
	public function addressModeW(value:AddressMode):Void;
	@:native("xgpu_gpu_sampler_descriptor_mag_filter")
	public function magFilter(value:FilterMode):Void;
	@:native("xgpu_gpu_sampler_descriptor_min_filter")
	public function minFilter(value:FilterMode):Void;
	@:native("xgpu_gpu_sampler_descriptor_mipmap_filter")
	public function mipmapFilter(value:MipmapFilterMode):Void;
	@:native("xgpu_gpu_sampler_descriptor_lod_min_clamp")
	public function lodMinClamp(value:Float):Void;
	@:native("xgpu_gpu_sampler_descriptor_lod_max_clamp")
	public function lodMaxClamp(value:Float):Void;
	@:native("xgpu_gpu_sampler_descriptor_compare")
	public function compare(value:CompareFunction):Void;
	@:native("xgpu_gpu_sampler_descriptor_max_anisotropy")
	public function maxAnisotropy(value:Int):Void;
	@:native("xgpu_gpu_sampler_descriptor_border_color")
	public function borderColor(value:BorderColor):Void;
}
