// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuSurface")
extern class GpuSurface {
	@:native("xgpu_gpu_surface_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_surface_preferred_format")
	public function preferredFormat(adapter:GpuAdapter):TextureFormat;
	@:native("xgpu_gpu_surface_acquire")
	public function acquire():GpuTextureView;
	@:native("xgpu_gpu_surface_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_surface_capabilities")
	public function capabilities(adapter:GpuAdapter):GpuSurfaceCapabilities;
}
