// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuSampler")
extern class GpuSampler {
	@:native("xidl_gpu_sampler_valid")
	public function valid():Bool;
	@:native("xidl_gpu_sampler_destroy")
	public function destroy():Void;
}
