// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuSurfaceConfiguration")
extern class GpuSurfaceConfiguration {
	@:native("xgpu_gpu_surface_configuration_new")
	public function new(format:TextureFormat, width:Int, height:Int);
	@:native("xgpu_gpu_surface_configuration_usage")
	public function usage(value:Int):Void;
	@:native("xgpu_gpu_surface_configuration_add_view_formats")
	public function addViewFormats(value:TextureFormat):Void;
	@:native("xgpu_gpu_surface_configuration_alpha_mode")
	public function alphaMode(value:AlphaMode):Void;
	@:native("xgpu_gpu_surface_configuration_present_mode")
	public function presentMode(value:PresentMode):Void;
	@:native("xgpu_gpu_surface_configuration_color_space")
	public function colorSpace(value:ColorSpace):Void;
	@:native("xgpu_gpu_surface_configuration_desired_maximum_frame_latency")
	public function desiredMaximumFrameLatency(value:Int):Void;
}
