// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuSamplerBindingLayout")
extern class GpuSamplerBindingLayout {
	@:native("xgpu_gpu_sampler_binding_layout_new")
	public function new();
	@:native("xgpu_gpu_sampler_binding_layout_type")
	public function type(value:SamplerBindingType):Void;
}
