// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuStencilFaceState")
extern class GpuStencilFaceState {
	@:native("xgpu_gpu_stencil_face_state_new")
	public function new();
	@:native("xgpu_gpu_stencil_face_state_compare")
	public function compare(value:CompareFunction):Void;
	@:native("xgpu_gpu_stencil_face_state_fail_op")
	public function failOp(value:StencilOperation):Void;
	@:native("xgpu_gpu_stencil_face_state_depth_fail_op")
	public function depthFailOp(value:StencilOperation):Void;
	@:native("xgpu_gpu_stencil_face_state_pass_op")
	public function passOp(value:StencilOperation):Void;
}
