// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuShader")
extern class GpuShader {
	@:native("xgpu_gpu_shader_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_shader_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_shader_messages")
	public function messages():String;
	@:native("xgpu_gpu_shader_get_compilation_info")
	public function getCompilationInfo():rayzor.concurrent.Future<GpuCompilationInfo>;
}
