// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTexture")
extern class GpuTexture {
	@:native("xidl_gpu_texture_valid")
	public function valid():Bool;
	@:native("xidl_gpu_texture_create_view")
	public function createView(descriptor:GpuTextureViewDescriptor):GpuTextureView;
	@:native("xidl_gpu_texture_destroy")
	public function destroy():Void;
	@:native("xidl_gpu_texture_width")
	public function width():Int;
	@:native("xidl_gpu_texture_height")
	public function height():Int;
	@:native("xidl_gpu_texture_depth_or_array_layers")
	public function depthOrArrayLayers():Int;
	@:native("xidl_gpu_texture_mip_level_count")
	public function mipLevelCount():Int;
	@:native("xidl_gpu_texture_sample_count")
	public function sampleCount():Int;
	@:native("xidl_gpu_texture_dimension")
	public function dimension():TextureDimension;
	@:native("xidl_gpu_texture_format")
	public function format():TextureFormat;
	@:native("xidl_gpu_texture_usage")
	public function usage():Int;
}
