// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTlasInstance")
extern class GpuTlasInstance {
	@:native("xidl_gpu_tlas_instance_new")
	public function new(blas:GpuBlas);
	@:native("xidl_gpu_tlas_instance_add_transform")
	public function addTransform(value:Float):Void;
	@:native("xidl_gpu_tlas_instance_custom_data")
	public function customData(value:Int):Void;
	@:native("xidl_gpu_tlas_instance_mask")
	public function mask(value:Int):Void;
}
