// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTlasDescriptor")
extern class GpuTlasDescriptor {
	@:native("xgpu_gpu_tlas_descriptor_new")
	public function new(maxInstances:Int);
	@:native("xgpu_gpu_tlas_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_tlas_descriptor_flags")
	public function flags(value:Int):Void;
	@:native("xgpu_gpu_tlas_descriptor_update_mode")
	public function updateMode(value:AccelerationStructureUpdateMode):Void;
}
