// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTexelCopyBufferInfo")
extern class GpuTexelCopyBufferInfo {
	@:native("xidl_gpu_texel_copy_buffer_info_new")
	public function new(buffer:GpuBuffer);
	@:native("xidl_gpu_texel_copy_buffer_info_offset")
	public function offset(value:haxe.Int64):Void;
	@:native("xidl_gpu_texel_copy_buffer_info_bytes_per_row")
	public function bytesPerRow(value:Int):Void;
	@:native("xidl_gpu_texel_copy_buffer_info_rows_per_image")
	public function rowsPerImage(value:Int):Void;
}
