// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTextureBindingLayout")
extern class GpuTextureBindingLayout {
	@:native("xgpu_gpu_texture_binding_layout_new")
	public function new();
	@:native("xgpu_gpu_texture_binding_layout_sample_type")
	public function sampleType(value:TextureSampleType):Void;
	@:native("xgpu_gpu_texture_binding_layout_view_dimension")
	public function viewDimension(value:TextureViewDimension):Void;
	@:native("xgpu_gpu_texture_binding_layout_multisampled")
	public function multisampled(value:Bool):Void;
}
