// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTlas")
extern class GpuTlas {
	@:native("xgpu_gpu_tlas_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_tlas_destroy")
	public function destroy():Void;
	@:native("xgpu_gpu_tlas_max_instances")
	public function maxInstances():Int;
	@:native("xgpu_gpu_tlas_set_instance")
	public function setInstance(index:Int, instance:GpuTlasInstance):Void;
	@:native("xgpu_gpu_tlas_clear_instance")
	public function clearInstance(index:Int):Void;
}
