// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTextureView")
extern class GpuTextureView {
	@:native("xidl_gpu_texture_view_valid")
	public function valid():Bool;
	@:native("xidl_gpu_texture_view_destroy")
	public function destroy():Void;
}
