// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTextureViewArray")
extern class GpuTextureViewArray {
	@:native("xidl_gpu_texture_view_array_new")
	public function new();
	@:native("xidl_gpu_texture_view_array_add_views")
	public function addViews(value:GpuTextureView):Void;
}
