// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTexelCopyBufferLayout")
extern class GpuTexelCopyBufferLayout {
	@:native("xgpu_gpu_texel_copy_buffer_layout_new")
	public function new();
	@:native("xgpu_gpu_texel_copy_buffer_layout_offset")
	public function offset(value:haxe.Int64):Void;
	@:native("xgpu_gpu_texel_copy_buffer_layout_bytes_per_row")
	public function bytesPerRow(value:Int):Void;
	@:native("xgpu_gpu_texel_copy_buffer_layout_rows_per_image")
	public function rowsPerImage(value:Int):Void;
}
