// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTextureView")
extern class GpuTextureView {
	@:native("xgpu_gpu_texture_view_valid")
	public function valid():Bool;
	@:native("xgpu_gpu_texture_view_destroy")
	public function destroy():Void;
}
