// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTextureViewDescriptor")
extern class GpuTextureViewDescriptor {
	@:native("xgpu_gpu_texture_view_descriptor_new")
	public function new();
	@:native("xgpu_gpu_texture_view_descriptor_label")
	public function label(value:String):Void;
	@:native("xgpu_gpu_texture_view_descriptor_format")
	public function format(value:TextureFormat):Void;
	@:native("xgpu_gpu_texture_view_descriptor_dimension")
	public function dimension(value:TextureViewDimension):Void;
	@:native("xgpu_gpu_texture_view_descriptor_usage")
	public function usage(value:Int):Void;
	@:native("xgpu_gpu_texture_view_descriptor_aspect")
	public function aspect(value:TextureAspect):Void;
	@:native("xgpu_gpu_texture_view_descriptor_base_mip_level")
	public function baseMipLevel(value:Int):Void;
	@:native("xgpu_gpu_texture_view_descriptor_mip_level_count")
	public function mipLevelCount(value:Int):Void;
	@:native("xgpu_gpu_texture_view_descriptor_base_array_layer")
	public function baseArrayLayer(value:Int):Void;
	@:native("xgpu_gpu_texture_view_descriptor_array_layer_count")
	public function arrayLayerCount(value:Int):Void;
	@:native("xgpu_gpu_texture_view_descriptor_swizzle")
	public function swizzle(value:String):Void;
}
