// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTexelCopyTextureInfo")
extern class GpuTexelCopyTextureInfo {
	@:native("xgpu_gpu_texel_copy_texture_info_new")
	public function new(texture:GpuTexture);
	@:native("xgpu_gpu_texel_copy_texture_info_mip_level")
	public function mipLevel(value:Int):Void;
	@:native("xgpu_gpu_texel_copy_texture_info_origin")
	public function origin(value:GpuOrigin3D):Void;
	@:native("xgpu_gpu_texel_copy_texture_info_aspect")
	public function aspect(value:TextureAspect):Void;
}
