// Generated by xidl-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTextureDescriptor")
extern class GpuTextureDescriptor {
	@:native("xidl_gpu_texture_descriptor_new")
	public function new(size:GpuExtent3D, format:TextureFormat, usage:Int);
	@:native("xidl_gpu_texture_descriptor_label")
	public function label(value:String):Void;
	@:native("xidl_gpu_texture_descriptor_mip_level_count")
	public function mipLevelCount(value:Int):Void;
	@:native("xidl_gpu_texture_descriptor_sample_count")
	public function sampleCount(value:Int):Void;
	@:native("xidl_gpu_texture_descriptor_dimension")
	public function dimension(value:TextureDimension):Void;
	@:native("xidl_gpu_texture_descriptor_add_view_formats")
	public function addViewFormats(value:TextureFormat):Void;
	@:native("xidl_gpu_texture_descriptor_texture_binding_view_dimension")
	public function textureBindingViewDimension(value:TextureViewDimension):Void;
}
