// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuTlasArray")
extern class GpuTlasArray {
	@:native("xgpu_gpu_tlas_array_new")
	public function new();
	@:native("xgpu_gpu_tlas_array_add_tlases")
	public function addTlases(value:GpuTlas):Void;
}
