// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuVertexBufferLayout")
extern class GpuVertexBufferLayout {
	@:native("xgpu_gpu_vertex_buffer_layout_new")
	public function new(arrayStride:haxe.Int64);
	@:native("xgpu_gpu_vertex_buffer_layout_step_mode")
	public function stepMode(value:VertexStepMode):Void;
	@:native("xgpu_gpu_vertex_buffer_layout_add_attributes")
	public function addAttributes(value:GpuVertexAttribute):Void;
}
