// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuVertexState")
extern class GpuVertexState {
	@:native("xgpu_gpu_vertex_state_new")
	public function new(module:GpuShader);
	@:native("xgpu_gpu_vertex_state_entry_point")
	public function entryPoint(value:String):Void;
	@:native("xgpu_gpu_vertex_state_add_constants")
	public function addConstants(key:String, value:Float):Void;
	@:native("xgpu_gpu_vertex_state_add_buffers")
	public function addBuffers(value:GpuVertexBufferLayout):Void;
}
