// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

@:native("rayzor::gpu::GpuVertexAttribute")
extern class GpuVertexAttribute {
	@:native("xgpu_gpu_vertex_attribute_new")
	public function new(format:VertexFormat, offset:haxe.Int64, shaderLocation:Int);
}
