// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class InstanceFlag {
	public static inline var DEBUG:Int = 1;
	public static inline var VALIDATION:Int = 2;
	public static inline var DISCARD_HAL_LABELS:Int = 4;
	public static inline var ALLOW_UNDERLYING_NONCOMPLIANT_ADAPTER:Int = 8;
	public static inline var GPU_BASED_VALIDATION:Int = 16;
	public static inline var VALIDATION_INDIRECT_CALL:Int = 32;
	public static inline var AUTOMATIC_TIMESTAMP_NORMALIZATION:Int = 64;
	public static inline var STRICT_WEBGPU_COMPLIANCE:Int = 128;
}
