// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract Limit(Int) from Int to Int {
	var MaxTextureDimension1D = 0;
	var MaxTextureDimension2D = 1;
	var MaxTextureDimension3D = 2;
	var MaxTextureArrayLayers = 3;
	var MaxBindGroups = 4;
	var MaxBindGroupsPlusVertexBuffers = 5;
	var MaxImmediateSize = 6;
	var MaxBindingsPerBindGroup = 7;
	var MaxDynamicUniformBuffersPerPipelineLayout = 8;
	var MaxDynamicStorageBuffersPerPipelineLayout = 9;
	var MaxSampledTexturesPerShaderStage = 10;
	var MaxSamplersPerShaderStage = 11;
	var MaxStorageBuffersPerShaderStage = 12;
	var MaxStorageBuffersInVertexStage = 13;
	var MaxStorageBuffersInFragmentStage = 14;
	var MaxStorageTexturesPerShaderStage = 15;
	var MaxStorageTexturesInVertexStage = 16;
	var MaxStorageTexturesInFragmentStage = 17;
	var MaxUniformBuffersPerShaderStage = 18;
	var MaxUniformBufferBindingSize = 19;
	var MaxStorageBufferBindingSize = 20;
	var MinUniformBufferOffsetAlignment = 21;
	var MinStorageBufferOffsetAlignment = 22;
	var MaxVertexBuffers = 23;
	var MaxBufferSize = 24;
	var MaxVertexAttributes = 25;
	var MaxVertexBufferArrayStride = 26;
	var MaxInterStageShaderVariables = 27;
	var MaxColorAttachments = 28;
	var MaxColorAttachmentBytesPerSample = 29;
	var MaxComputeWorkgroupStorageSize = 30;
	var MaxComputeInvocationsPerWorkgroup = 31;
	var MaxComputeWorkgroupSizeX = 32;
	var MaxComputeWorkgroupSizeY = 33;
	var MaxComputeWorkgroupSizeZ = 34;
	var MaxComputeWorkgroupsPerDimension = 35;
}
