// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract NativeLimit(Int) from Int to Int {
	var MaxBindingArrayElementsPerShaderStage = 0;
	var MaxBindingArrayAccelerationStructureElementsPerShaderStage = 1;
	var MaxBindingArraySamplerElementsPerShaderStage = 2;
	var MaxNonSamplerBindings = 3;
	var MaxTaskWorkgroupTotalCount = 4;
	var MaxTaskWorkgroupsPerDimension = 5;
	var MaxMeshWorkgroupTotalCount = 6;
	var MaxMeshWorkgroupsPerDimension = 7;
	var MaxTaskInvocationsPerWorkgroup = 8;
	var MaxTaskInvocationsPerDimension = 9;
	var MaxMeshInvocationsPerWorkgroup = 10;
	var MaxMeshInvocationsPerDimension = 11;
	var MaxTaskPayloadSize = 12;
	var MaxMeshOutputVertices = 13;
	var MaxMeshOutputPrimitives = 14;
	var MaxMeshOutputLayers = 15;
	var MaxMeshMultiviewViewCount = 16;
	var MaxBlasPrimitiveCount = 17;
	var MaxBlasGeometryCount = 18;
	var MaxTlasInstanceCount = 19;
	var MaxAccelerationStructuresPerShaderStage = 20;
	var MaxBuffersAndAccelerationStructuresPerShaderStage = 21;
	var MaxMultiviewViewCount = 22;
	var MaxRayDispatchCount = 23;
	var MaxRayRecursionDepth = 24;
}
