// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class PipelineStatistic {
	public static inline var VERTEX_SHADER_INVOCATIONS:Int = 1;
	public static inline var CLIPPER_INVOCATIONS:Int = 2;
	public static inline var CLIPPER_PRIMITIVES_OUT:Int = 4;
	public static inline var FRAGMENT_SHADER_INVOCATIONS:Int = 8;
	public static inline var COMPUTE_SHADER_INVOCATIONS:Int = 16;
}
