// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract PresentMode(Int) from Int to Int {
	var AutoVsync = 0;
	var AutoNoVsync = 1;
	var Fifo = 2;
	var FifoRelaxed = 3;
	var Immediate = 4;
	var Mailbox = 5;
}
