// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract PrimitiveTopology(Int) from Int to Int {
	var PointList = 0;
	var LineList = 1;
	var LineStrip = 2;
	var TriangleList = 3;
	var TriangleStrip = 4;
}
