// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class ShaderStage {
	public static inline var VERTEX:Int = 0x1;
	public static inline var FRAGMENT:Int = 0x2;
	public static inline var COMPUTE:Int = 0x4;
	public static inline var TASK:Int = 8;
	public static inline var MESH:Int = 16;
}
