// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract StorageTextureAccess(Int) from Int to Int {
	var WriteOnly = 0;
	var ReadOnly = 1;
	var ReadWrite = 2;
	var Atomic = 3;
}
