// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class TextureUsage {
	public static inline var COPY_SRC:Int = 0x01;
	public static inline var COPY_DST:Int = 0x02;
	public static inline var TEXTURE_BINDING:Int = 0x04;
	public static inline var STORAGE_BINDING:Int = 0x08;
	public static inline var RENDER_ATTACHMENT:Int = 0x10;
	public static inline var TRANSIENT_ATTACHMENT:Int = 0x20;
	public static inline var STORAGE_ATOMIC:Int = 65536;
}
