// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract TextureViewDimension(Int) from Int to Int {
	var D1d = 0;
	var D2d = 1;
	var D2dArray = 2;
	var Cube = 3;
	var CubeArray = 4;
	var D3d = 5;
}
