// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

enum abstract TextureSampleType(Int) from Int to Int {
	var Float = 0;
	var UnfilterableFloat = 1;
	var Depth = 2;
	var Sint = 3;
	var Uint = 4;
}
