// Generated by xgpu-bindgen. Do not edit by hand.
package rayzor.gpu;

class TextureFormatFeature {
	public static inline var FILTERABLE:Int = 1;
	public static inline var MULTISAMPLE_X2:Int = 2;
	public static inline var MULTISAMPLE_X4:Int = 4;
	public static inline var MULTISAMPLE_X8:Int = 8;
	public static inline var MULTISAMPLE_X16:Int = 16;
	public static inline var MULTISAMPLE_RESOLVE:Int = 32;
	public static inline var STORAGE_READ_ONLY:Int = 64;
	public static inline var STORAGE_WRITE_ONLY:Int = 128;
	public static inline var STORAGE_READ_WRITE:Int = 256;
	public static inline var STORAGE_ATOMIC:Int = 512;
	public static inline var BLENDABLE:Int = 1024;
}
